import type { Me } from "@/lib/auth/types";
import type { Referral,Investigation,Preparation } from "./types";
export function canContinuity(user:Me|null,...permissions:string[]){return !!user&&user.roles.some(r=>r.code==="TB_OFFICER")&&permissions.every(p=>user.permissions.includes(p));}
export function continuityNavigation(user:Me|null){return [...(canContinuity(user,"REFERRAL_READ")?[{label:"Rujukan",href:"/referrals"}]:[]),...(canContinuity(user,"CONTACT_READ")?[{label:"Investigasi kontak",href:"/contact-investigations"}]:[])];}
export const assigned=(user:Me|null,id:string|null|undefined)=>!!id&&!!user?.activeFacilities.some(f=>f.id===id);
export function sendKind(p:Preparation){if(p.inFlightReferral)return null;if(p.caseStatus==="REFERRED"&&p.preTreatmentDestination&&!p.openTreatment)return "PRE_TREATMENT_REFERRAL";if(p.caseStatus==="ACTIVE"&&p.openTreatment?.status==="ACTIVE")return "TREATMENT_TRANSFER";return null;}
export function referralActions(user:Me|null,r:Referral){if(!canContinuity(user,"REFERRAL_WRITE"))return [];const source=assigned(user,r.sourceFacility.id),destination=assigned(user,r.destinationFacility.id);return [...(source&&r.status==="SENT"?["cancel"]:[]),...(destination&&r.status==="SENT"?["receive"]:[]),...(destination&&r.status==="RECEIVED"?["return","report"]:[])] as const;}
export function workingFacility(i:Investigation){return i.workflowType==="INTERNAL"?i.sourceFacility:i.workflowType==="OUTGOING_REFERRAL"?i.destinationFacility:null;}
export function investigationActions(user:Me|null,i:Investigation){if(!canContinuity(user,"CONTACT_WRITE"))return [];const outgoing=i.workflowType==="OUTGOING_REFERRAL",source=assigned(user,i.sourceFacility.id),destination=assigned(user,i.destinationFacility?.id);return [...(outgoing&&source&&i.status==="SENT"?["cancel"]:[]),...(outgoing&&destination&&i.status==="SENT"?["receive"]:[]),...(outgoing&&destination&&i.status==="RECEIVED"?["start"]:[]),...(outgoing&&destination&&["RECEIVED","IN_PROGRESS"].includes(i.status)?["return"]:[]),...(assigned(user,workingFacility(i)?.id)&&i.status==="IN_PROGRESS"?["complete"]:[])] as const;}
export const canStartTpt=(user:Me|null,i:Investigation)=>canContinuity(user,"TPT_WRITE")&&assigned(user,workingFacility(i)?.id)&&i.status==="COMPLETED"&&i.activeTbExcluded===true&&i.tptEligible===true;
