import { z } from "@/lib/validation";
import { identityConfirmationSchema } from "@/features/clinical-intake/schemas";
export { identityConfirmationSchema };
const id=z.uuid(),version=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),text=z.string().nullable(),date=z.iso.date(),time=z.iso.datetime({offset:true}),masked=z.string().regex(/^\*{3}.{0,4}$/).nullable();
export const optionSchema=z.strictObject({code:z.string().min(1),name:z.string()});
export const facilitySchema=z.strictObject({id,name:z.string()});
export const openTreatmentSchema=z.strictObject({id,status:z.enum(["PLANNED","ACTIVE","PAUSED","TRANSFERRED","COMPLETED","STOPPED","CANCELLED"]),startDate:date,plannedEndDate:date.nullable(),regimenCode:text,regimenName:text});
export const preparationSchema=z.strictObject({caseId:id,caseStatus:z.string(),caseCategoryCode:text,sourceFacility:facilitySchema,preTreatmentDestination:facilitySchema.nullable(),openTreatment:openTreatmentSchema.nullable(),inFlightReferral:z.boolean()});
const page=<T extends z.ZodType>(item:T)=>z.strictObject({content:z.array(item),page:version,size:z.number().int().min(1).max(50),totalElements:version});
export const facilityPageSchema=page(facilitySchema.extend({facilityTypeCode:text,provinceCode:text,regencyCode:text}));
export const referralReferencesSchema=z.strictObject({referralTypes:z.array(optionSchema),referralStatuses:z.array(optionSchema)});
export const contactReferencesSchema=z.strictObject({workflowTypes:z.array(optionSchema),creatableWorkflowTypes:z.array(optionSchema),investigationStatuses:z.array(optionSchema)});
export const tptReferencesSchema=z.strictObject({preventiveRegimens:z.array(optionSchema.extend({caseCategoryCode:z.enum(["TB_SO","TB_RO"])})),tptStatuses:z.array(optionSchema),durationUnits:z.array(optionSchema)});
export const referralSchema=z.strictObject({id,version,referralType:z.enum(["PRE_TREATMENT_REFERRAL","TREATMENT_TRANSFER"]),status:z.enum(["DRAFT","SENT","RECEIVED","REPORTED","CANCELLED","RETURNED"]),sentAt:time,receivedAt:time.nullable(),patientReportedAt:time.nullable(),cancelledAt:time.nullable(),sourceFacility:facilitySchema,destinationFacility:facilitySchema,patient:z.strictObject({id,fullName:z.string()}),tbCase:z.strictObject({id,categoryCode:text,status:z.string()}),treatment:openTreatmentSchema.nullable(),notes:text,cancelReason:text,returnReason:text});
export const referralPageSchema=page(referralSchema);
const workflow=z.enum(["INTERNAL","INCOMING_REFERRAL","OUTGOING_REFERRAL"]),investigationStatus=z.enum(["NEW","SENT","RECEIVED","IN_PROGRESS","COMPLETED","RETURNED","CANCELLED"]),tptStatus=z.enum(["PLANNED","ACTIVE","COMPLETED","STOPPED","LOST_TO_FOLLOW_UP","CANCELLED"]);
export const contactSchema=z.strictObject({id,version,fullName:z.string(),birthDate:date.nullable(),sexCode:text,phone:masked,address:text,relationshipToIndexCase:text,householdContact:z.boolean().nullable(),linkedPatient:z.boolean(),investigations:z.array(z.strictObject({id,version,workflowType:workflow,status:investigationStatus,requestedAt:time})),tpt:z.array(z.strictObject({id,version,status:tptStatus,startDate:date,facility:facilitySchema.nullable()}))});
export const contactPageSchema=page(contactSchema);
export const investigationSchema=z.strictObject({id,version,workflowType:workflow,status:investigationStatus,requestedAt:time,receivedAt:time.nullable(),investigatedAt:time.nullable(),eligibilityAssessedAt:time.nullable(),sourceFacility:facilitySchema,destinationFacility:facilitySchema.nullable(),contact:z.strictObject({id,fullName:z.string(),birthDate:date.nullable(),sexCode:text,phone:masked}),indexCase:z.strictObject({id,categoryCode:text}),resultCode:text,activeTbExcluded:z.boolean().nullable(),tptEligible:z.boolean().nullable(),notes:text,returnReason:text});
export const investigationPageSchema=page(investigationSchema);
export const tptSchema=z.strictObject({id,version,contactId:id,indexCaseId:id.nullable(),facility:facilitySchema,status:tptStatus,regimenCode:text,regimenName:text,regimenDescription:text,startDate:date,plannedEndDate:date.nullable(),actualEndDate:date.nullable(),durationValue:z.number().int().nullable(),durationUnit:text,weightKg:z.number().nullable(),drugSource:text,notes:text,closureReason:text});
export const tptPageSchema=page(tptSchema);
