spring.application.name=tbcall
spring.datasource.url=${TBCALL_DB_URL}
spring.datasource.username=${TBCALL_DB_USER}
spring.datasource.password=${TBCALL_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
spring.flyway.enabled=true
