// Serial real-stack smoke runner. No mocks, mutation retries, trace/HAR/screenshot.
import { chromium } from '/runner/node_modules/playwright/index.mjs';
import { writeFileSync, readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { extendedDefinitions, runExtended } from './extended.mjs';
const origin='https://app.tbcall.test:3443', api='/api/tbcall/v1';
const definitions=[
 ['P01','Anonymous CSRF initialization and rejection','anonymous','TLS, isolation, migration gates passed'],
 ['P02','Session cookie attributes, CSRF rotation and logout','bootstrap administrator','P01'],
 ['A01','Seven-role synthetic account provisioning and two facilities','system administrator','P02'],
 ['A02','Facility administration scope and role restrictions','facility administrator, lab staff','A01'],
 ['C01','Synthetic registration, diagnosis and confirmed case','facility-A TB officer','A01'],
 ['C02','Cross-facility and wrong-role clinical denials','facility-B officer, lab staff, program monitor','C01'],
 ['L01','Exact verified patient account resolution and safe masking','facility-A TB officer','C01'],
 ['L02','Authoritative patient-link state, role grant and safe self projection','officer, patient','L01'],
 ['L03','Identity-bound patient revocation and immediate role loss','officer, patient','L02'],
 ['S01','Supporter record list/detail, exact resolution and linking','officer, supporter','C01'],
 ['S02','Supporter safe portal API and authoritative unlink','officer, supporter','S01'],
 ['E01','Authoritative GET ETag and stale update rejection','facility-A TB officer','C01'],
 ['B01','Rendered login/logout, CSP and runtime errors','facility-A TB officer','C01'],
 ['B02','Patient linking UI explicit acknowledgement and confirmation','facility-A TB officer','B01,L03'],
 ['B03','Patient portal rendering, revocation and protected-state clearing','patient, officer','B02'],
 ['B04','Supporter record and linking UI explicit confirmation','facility-A TB officer','B01,S02'],
 ['B05','Supporter portal rendering and unlink access loss','supporter, officer','B04'],
 ['B06','Stale UI mutation rejected once without automatic replay','facility-A TB officer','B01,E01'],
 ['B07','Logout/account switch clears protected information','TB officer, lab staff','B01'],
 ['B08','Live membership loss hides protected officer information','facility-A TB officer, system administrator','B07'],
];
const results=[...definitions,...extendedDefinitions].map(([id,objective,actor,preconditions,expected])=>({id,objective,actor,preconditions,status:'NOT RUN',operations:[],expected:expected??'Source-derived assertions in run-smoke.mjs',actual:'Not executed'}));
let current, browser, activePage, stage='preflight';
const dbAssertions=[];
function observe(assertion,actual){current.operations.push({method:'ASSERT',assertion,expected:true,actual});}
function db(key,sql,expected){dbAssertions.push({scenario:current.id,key,sql,expected});writeFileSync('/tmp/e2e-db-assertions.json',JSON.stringify(dbAssertions));}
const contexts=[];
function save(){let memoryEvents='unavailable';try{memoryEvents=readFileSync('/sys/fs/cgroup/memory.events','utf8');}catch{}writeFileSync('/tmp/e2e-results.json',JSON.stringify({baseline:'ce7c5f353dd4593c86775f957a2f7d826f9e7337',workers:1,mutationRetries:0,stage,memoryEvents,results},null,2));}
function check(value,code){if(!value)throw new Error(code);}
function safe(code){if(/strict mode violation/.test(code))return 'UI_LOCATOR_AMBIGUOUS';if(/Target.*closed|page.*crashed/i.test(code))return 'BROWSER_TARGET_CLOSED_OR_CRASHED';return /^[A-Z0-9_]+$/.test(code)?code:'BROWSER_OR_TRANSPORT_FAILURE';}
async function scenario(id,fn){current=results.find(r=>r.id===id);const prerequisites=current.preconditions.match(/\b[A-Z]\d\d\b/g)??[];if(prerequisites.some(p=>results.find(r=>r.id===p)?.status!=='PASS')){current.status='BLOCKED';current.actual='Required predecessor did not pass';save();return false;}try{await fn();current.status='PASS';current.actual='All recorded status and state assertions passed';return true;}catch(e){current.status='FAIL';current.actual=safe(e.message);current.failureKind=e.name==='TimeoutError'?'TIMEOUT':safe(e.name.toUpperCase());console.log(JSON.stringify({id,status:'FAIL',classification:current.actual,lastStep:current.lastStep,failureKind:current.failureKind}));if(stage==='preflight')throw e;return false;}finally{save();}}
function operation(method,path,status,expected){current?.operations.push({method,contract:path.replace(/[0-9a-f]{8}-[0-9a-f-]{27}/gi,'{id}').replace(/\?.*$/,'?{parameters}'),expectedStatus:expected,actualStatus:status});}
async function client(){const context=await browser.newContext({ignoreHTTPSErrors:false});contexts.push(context);const page=await context.newPage();page.setDefaultTimeout(25000);page.on('response',r=>{if(!current?.id.startsWith('B'))return;const q=r.request(),url=new URL(r.url());if(url.origin!==origin)return;if(q.resourceType()==='document'||(url.pathname.startsWith(api)&&q.method()!=='GET'))current.operations.push({method:q.method(),contract:url.pathname.replace(/[0-9a-f]{8}-[0-9a-f-]{27}/gi,'{id}'),actualStatus:r.status(),source:'Actual browser network response; no request/response payload recorded'});});await page.goto(origin+'/__e2e/probe');return {context,page};}
async function request(c,method,path,body,expected=200,options={}){
 const result=await c.page.evaluate(async ({url,method,body,options})=>{
  const cookies=Object.fromEntries(document.cookie.split('; ').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i),decodeURIComponent(v.slice(i+1))];}));
  const headers={Accept:'application/json',...options.headers};if(body!==undefined)headers['Content-Type']='application/json';
  if(method!=='GET'&&!options.omitCsrf)headers['X-XSRF-TOKEN']=options.invalidCsrf?'invalid-task-token':cookies['XSRF-TOKEN']??'';
  const r=await fetch(url,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(25000)});
  const text=await r.text();let data;try{data=text?JSON.parse(text):null;}catch{data=null;}
  return {status:r.status,data,etag:r.headers.get('etag')};
 },{url:origin+api+path,method,body,options});
 operation(method,path,result.status,expected);check(Array.isArray(expected)?expected.includes(result.status):result.status===expected,'HTTP_STATUS_MISMATCH');return result;
}
async function initialize(c){await request(c,'GET','/me',undefined,401);}
async function login(c,account){await initialize(c);await request(c,'POST','/auth/login',{identity:account.email,password:account.password});return (await request(c,'GET','/me')).data;}
function roles(me){return me.roles.map(r=>r.code);}
const actors={},fixture={};
const admin={email:process.env.TBCALL_BOOTSTRAP_EMAIL,password:process.env.TBCALL_BOOTSTRAP_PASSWORD};
async function provision(label,role,facility){const c=await client();await initialize(c);const account={email:`e2e-${label}-${randomUUID()}@example.invalid`,password:'F6b!'+randomUUID()};
 const registration=(await request(c,'POST','/auth/register',account,201)).data;check(registration.verificationTokens?.length===1,'VERIFICATION_TOKEN_CONFIGURATION');
 await request(c,'POST','/auth/verify',{token:registration.verificationTokens[0].token});account.id=registration.id;
 if(facility)await request(actors.admin,'POST',`/admin/facilities/${facility}/users/${account.id}`,{primary:true});
 if(role)await request(actors.admin,'POST',`/admin/users/${account.id}/roles/${role}`);
 const me=await login(c,account);check(!role||roles(me).includes(role),'ROLE_ASSIGNMENT_FAILED');actors[label]={...c,...account};return me;
}
async function uiLogin(c,account){await c.page.goto(origin+'/login');await c.page.getByLabel('Email atau nomor telepon').fill(account.email);await c.page.getByLabel('Kata sandi',{exact:true}).fill(account.password);current.lastStep='UI_LOGIN_SUBMIT';await c.page.getByRole('button',{name:'Masuk',exact:true}).click();current.lastStep='UI_LOGIN_WAIT_AUTHENTICATED_SHELL';await c.page.getByRole('button',{name:'Keluar',exact:true}).waitFor();current?.operations.push({method:'UI',contract:'Fill login form, click Masuk, await Keluar',expected:'Authenticated shell',actual:'Authenticated shell rendered'});}
async function visible(page,locator){await locator.waitFor({state:'visible'});}
async function observeSessionRefresh(c,expectedRole,assigned){current.lastStep='UI_WAIT_AUTHORITATIVE_SESSION_REFRESH';const response=c.page.waitForResponse(r=>r.url()===origin+api+'/me'&&r.request().method()==='GET');await c.page.bringToFront();await c.page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));const r=await response;check(r.status()===200,'UI_SESSION_REFRESH_STATUS');const me=await r.json();check(roles(me).includes(expectedRole)===assigned,'UI_SESSION_REFRESH_ROLE');operation('UI_REFRESH','/me',r.status(),200);}
async function patientPage(c){await c.page.goto(origin+'/patients/'+fixture.patient);current.lastStep='UI_PATIENT_WAIT_HEADING';await visible(c.page,c.page.getByRole('heading',{name:'Detail pasien',exact:true}));current.lastStep='UI_PATIENT_WAIT_SYNTHETIC_DISPLAY';await visible(c.page,c.page.getByText(fixture.name,{exact:true}).first());}
const acknowledgement='Saya telah memeriksa identitas akun tujuan dan kewenangan orang tersebut untuk mengakses informasi pasien yang terkait.';
async function patientUiLink(){const page=actors.uiOfficer.page,section=page.getByRole('region',{name:'Akun pasien'});await patientPage(actors.uiOfficer);
 await section.getByLabel('Email atau telepon login terverifikasi (persis)').fill(actors.patient.email);await section.getByRole('button',{name:'Cari akun terverifikasi',exact:true}).click();
 await section.getByLabel(acknowledgement).check();await section.getByRole('button',{name:'Periksa tautan pasien',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Tautkan akun pasien',exact:true});await visible(page,dialog);check(!(await request(actors.officer,'GET',`/patients/${fixture.patient}/account-link`)).data.link,'PRECONFIRM_PATIENT_LINK_EXISTS');
 await dialog.getByRole('button',{name:'Konfirmasi tautkan akun pasien',exact:true}).click();await visible(page,page.getByText('Tautan akun pasien tersimpan.',{exact:true}));
 const link=await request(actors.officer,'GET',`/patients/${fixture.patient}/account-link`);check(link.etag&&link.data.link.userId===actors.patient.id,'UI_PATIENT_LINK_STATE');
}
async function patientUiRevoke(){const p=actors.uiOfficer.page,s=p.getByRole('region',{name:'Akun pasien'});await patientPage(actors.uiOfficer);await s.getByRole('button',{name:'Cabut tautan pasien',exact:true}).click();const d=p.getByRole('dialog',{name:'Cabut tautan pasien',exact:true});await d.getByRole('button',{name:'Konfirmasi cabut tautan pasien',exact:true}).click();await visible(p,p.getByText('Tautan akun pasien dicabut.',{exact:true}));}
async function main(){save();browser=await chromium.launch({channel:'chromium',headless:true,chromiumSandbox:true});
 await scenario('P01',async()=>{actors.admin=await client();const c=actors.admin;await initialize(c);const csrf=(await c.context.cookies()).find(x=>x.name==='XSRF-TOKEN');check(csrf&&csrf.secure&&!csrf.httpOnly&&csrf.sameSite==='Strict','CSRF_COOKIE_FLAGS');
  const missing=await request(c,'POST','/auth/login',{identity:admin.email,password:admin.password},403,{omitCsrf:true});const invalid=await request(c,'POST','/auth/login',{identity:admin.email,password:admin.password},403,{invalidCsrf:true});check(missing.data.code==='CSRF_INVALID'&&invalid.data.code==='CSRF_INVALID','CSRF_REJECTION_CODE');current.operations.push({method:'OBSERVE',contract:'CSRF cookie Secure/Strict/script-readable; missing and invalid header',expected:'Protected cookie and CSRF_INVALID',actual:'Flags and both rejection codes confirmed'});
 });
 await scenario('P02',async()=>{const c=actors.admin;const before=(await c.context.cookies()).find(x=>x.name==='XSRF-TOKEN')?.value;await request(c,'POST','/auth/login',{identity:admin.email,password:admin.password});const me=(await request(c,'GET','/me')).data;check(roles(me).includes('SYSTEM_ADMIN'),'BOOTSTRAP_ROLE');check((await c.context.cookies()).find(x=>x.name==='XSRF-TOKEN')?.value!==before,'LOGIN_CSRF_ROTATION');
  const session=(await c.context.cookies()).find(x=>x.name==='TBCALL_SESSION');check(session&&session.secure&&session.httpOnly&&session.sameSite==='Strict','SESSION_COOKIE_FLAGS');
  check(!(await c.page.evaluate(()=>document.cookie)).includes('TBCALL_SESSION'),'HTTPONLY_SCRIPT_EXPOSURE');
  await request(c,'POST','/auth/logout',undefined,204);check(!(await c.context.cookies()).some(x=>x.name==='TBCALL_SESSION'),'LOGOUT_SESSION_NOT_REMOVED');await request(c,'GET','/me',undefined,401);
 });
 stage='provisioning';await login(actors.admin,admin);await scenario('A01',async()=>{const refs=(await request(actors.admin,'GET','/admin/reference-data')).data;check(refs.facilityTypes.length>0,'FACILITY_CATALOG_EMPTY');
  fixture.facilityA=(await request(actors.admin,'POST','/admin/facilities',{name:'E2E synthetic facility A',facilityTypeCode:refs.facilityTypes[0].code},201)).data.id;
  fixture.facilityB=(await request(actors.admin,'POST','/admin/facilities',{name:'E2E synthetic facility B',facilityTypeCode:refs.facilityTypes[0].code},201)).data.id;
  await provision('facilityAdmin','FACILITY_ADMIN',fixture.facilityA);await provision('officer','TB_OFFICER',fixture.facilityA);await provision('lab','LAB_STAFF',fixture.facilityA);await provision('monitor','PROGRAM_MONITOR');
  const patient=await provision('patient');const supporter=await provision('supporter');check(!roles(patient).includes('PATIENT')&&!roles(supporter).includes('TREATMENT_SUPPORTER'),'LINK_ROLE_PREMATURE');await provision('crossOfficer','TB_OFFICER',fixture.facilityB);
 });
 stage='smoke';await scenario('A02',async()=>{const f=await request(actors.admin,'GET',`/admin/facilities/${fixture.facilityA}`);check(f.etag,'FACILITY_GET_ETAG');
  await request(actors.facilityAdmin,'GET','/admin/reference-data');await request(actors.facilityAdmin,'POST',`/admin/facilities/${fixture.facilityA}/users/${actors.lab.id}`,{primary:true});
  await request(actors.facilityAdmin,'POST',`/admin/facilities/${fixture.facilityB}/users/${actors.lab.id}`,{primary:true},403);
  await request(actors.facilityAdmin,'GET',`/admin/facilities/${fixture.facilityA}`,undefined,403);await request(actors.lab,'GET','/admin/reference-data',undefined,403);
  await request(actors.admin,'POST',`/admin/users/${actors.patient.id}/roles/PATIENT`,undefined,400);await request(actors.admin,'POST',`/admin/users/${actors.supporter.id}/roles/TREATMENT_SUPPORTER`,undefined,400);
 });
 await scenario('C01',async()=>{const c=actors.officer,refs=(await request(c,'GET','/clinical-reference-data')).data,today=new Date().toISOString().slice(0,10);fixture.name='E2E synthetic patient';fixture.identity='E2E-SYNTHETIC-'+randomUUID();
  const reg=await request(c,'POST','/registrations',{facilityId:fixture.facilityA,registrationDate:today,suspectTypeCode:refs.suspectTypes[0].code,previousTreatmentCategoryCode:refs.previousTreatmentCategories[0].code,newPatient:{fullName:fixture.name,citizenship:'WNA',otherIdentityNumber:fixture.identity,birthDate:'1990-01-01',birthDateUnknown:false,sexCode:refs.sexCodes[0].code}},201);
  fixture.registration=reg.data.id;fixture.patient=reg.data.patient.patientId;const r=await request(c,'GET',`/registrations/${fixture.registration}`);check(r.etag&&r.data.status==='OPEN','REGISTRATION_STATE');
  const diag=await request(c,'POST',`/registrations/${fixture.registration}/diagnoses`,{diagnosisDate:today,anatomicalSiteCode:refs.anatomicalSites[0].code,diagnosisTypeCode:refs.diagnosisTypes[0].code,diagnosisResult:'Synthetic smoke fixture only',treatmentDisposition:'TREAT_HERE'},201,{headers:{'If-Match':r.etag}});
  const diagnosed=await request(c,'GET',`/registrations/${fixture.registration}`);check(diagnosed.data.status==='DIAGNOSED'&&diagnosed.etag!==r.etag,'DIAGNOSIS_TRANSITION');check(refs.caseCategories.some(x=>x.code==='TB_SO'),'CASE_CATALOG');
  const confirmed=await request(c,'POST',`/registrations/${fixture.registration}/cases`,{diagnosisId:diag.data.id,caseCategoryCode:'TB_SO',previousTreatmentCategoryCode:refs.previousTreatmentCategories[0].code},201,{headers:{'If-Match':diagnosed.etag}});fixture.case=confirmed.data.id;check(confirmed.data.status==='ACTIVE','CASE_ACTIVE');
 });
 await scenario('C02',async()=>{for(const actor of [actors.crossOfficer,actors.lab,actors.monitor]){const denial=actor===actors.crossOfficer?404:403;await request(actor,'GET',`/patients/${fixture.patient}`,undefined,denial);await request(actor,'GET',`/cases/${fixture.case}`,undefined,denial);}await request(actors.crossOfficer,'POST',`/patients/${fixture.patient}/account-link/resolve-user`,{identity:actors.patient.email},403);});
 await scenario('L01',async()=>{const found=(await request(actors.officer,'POST',`/patients/${fixture.patient}/account-link/resolve-user`,{identity:actors.patient.email})).data;check(found.userId===actors.patient.id,'EXACT_RESOLUTION');check(!JSON.stringify(found).includes(actors.patient.email),'LOOKUP_EXACT_IDENTITY_LEAK');});
 await scenario('L02',async()=>{const c=actors.officer;const empty=await request(c,'GET',`/patients/${fixture.patient}/account-link`);check(!empty.etag&&!empty.data.link,'EMPTY_LINK_ETAG');await request(c,'GET',`/patients/${fixture.patient}/account-link/precondition?userId=${actors.patient.id}`);
  await request(c,'POST',`/patients/${fixture.patient}/account-link`,{userId:actors.patient.id},201);const state=await request(c,'GET',`/patients/${fixture.patient}/account-link`);check(state.etag&&state.data.link.userId===actors.patient.id,'PATIENT_GET_ETAG');const me=(await request(actors.patient,'GET','/me')).data;check(roles(me).includes('PATIENT'),'PATIENT_ROLE_GRANT');const self=(await request(actors.patient,'GET','/me/patient')).data;check(self.fullName===fixture.name,'PATIENT_PROJECTION');check(!JSON.stringify(self).includes(fixture.identity)&&!('nik'in self)&&!('bpjsNumber'in self),'PATIENT_PROJECTION_PRIVACY');});
 await scenario('L03',async()=>{const c=actors.officer,state=await request(c,'GET',`/patients/${fixture.patient}/account-link`);await request(c,'DELETE',`/patients/${fixture.patient}/account-link`,undefined,428,{headers:{'If-Match':state.etag}});await request(c,'DELETE',`/patients/${fixture.patient}/account-links/${state.data.link.id}`,undefined,200,{headers:{'If-Match':state.etag}});check(!roles((await request(actors.patient,'GET','/me')).data).includes('PATIENT'),'PATIENT_ROLE_REVOCATION');await request(actors.patient,'GET','/me/patient',undefined,403);});
 await scenario('S01',async()=>{const c=actors.officer,record=await request(c,'POST',`/cases/${fixture.case}/supporters`,{supporterType:'PMO',fullName:'E2E synthetic supporter'},201);fixture.supporter=record.data.id;const list=(await request(c,'GET',`/cases/${fixture.case}/supporters`)).data;check(list.content.some(x=>x.id===fixture.supporter),'SUPPORTER_LIST');const detail=await request(c,'GET',`/cases/${fixture.case}/supporters/${fixture.supporter}`);check(detail.etag,'SUPPORTER_GET_ETAG');const candidate=(await request(c,'POST',`/cases/${fixture.case}/supporters/${fixture.supporter}/account-link/resolve-user`,{identity:actors.supporter.email})).data;check(candidate.userId===actors.supporter.id&&!JSON.stringify(candidate).includes(actors.supporter.email),'SUPPORTER_RESOLUTION_PRIVACY');await request(c,'POST',`/cases/${fixture.case}/supporters/${fixture.supporter}/account-link`,{userId:actors.supporter.id},200,{headers:{'If-Match':detail.etag}});check(roles((await request(actors.supporter,'GET','/me')).data).includes('TREATMENT_SUPPORTER'),'SUPPORTER_ROLE_GRANT');});
 await scenario('S02',async()=>{const c=actors.officer;const portal=await request(actors.supporter,'GET',`/me/supporting-cases/${fixture.case}/treatment`,undefined,404);check(portal.data.status===404,'EMPTY_SAFE_TREATMENT_PROJECTION');const detail=await request(c,'GET',`/cases/${fixture.case}/supporters/${fixture.supporter}`);await request(c,'DELETE',`/cases/${fixture.case}/supporters/${fixture.supporter}/account-link`,undefined,200,{headers:{'If-Match':detail.etag}});check(!roles((await request(actors.supporter,'GET','/me')).data).includes('TREATMENT_SUPPORTER'),'SUPPORTER_ROLE_REVOCATION');await request(actors.supporter,'GET',`/me/supporting-cases/${fixture.case}/treatment`,undefined,403);});
 await scenario('E01',async()=>{const c=actors.officer,original=await request(c,'GET',`/patients/${fixture.patient}`);check(original.etag,'PATIENT_GET_ETAG');await request(c,'PATCH',`/patients/${fixture.patient}`,{birthPlace:'E2E first update'},200,{headers:{'If-Match':original.etag}});await request(c,'PATCH',`/patients/${fixture.patient}`,{birthPlace:'E2E stale update'},409,{headers:{'If-Match':original.etag}});const state=await request(c,'GET',`/patients/${fixture.patient}`);check(state.data.demographics.birthPlace==='E2E first update'&&state.etag!==original.etag,'STALE_WRITE_STATE');});
 await browserScenarios();check(results.slice(0,20).every(r=>r.status==='PASS'),'BASELINE_REPEAT_GATE_FAILED');stage='extended';save();await runExtended({scenario,request,check,actors,fixture,client,login,provision,observe,db,uiLogin,origin});stage='complete';save();
}
// Browser scenarios are implemented below, always serial and through existing UI.
async function browserScenarios(){
 await scenario('B01',async()=>{const c=await client();actors.uiOfficer=c;let errors=0,violations=0;c.page.on('pageerror',()=>errors++);await c.page.addInitScript(()=>{window.__e2eCsp=0;document.addEventListener('securitypolicyviolation',()=>window.__e2eCsp++);});
  const response=await c.page.goto(origin+'/login');const csp=response.headers()['content-security-policy'];check(csp?.includes("connect-src 'self'")&&csp.includes("object-src 'none'")&&!csp.includes("'unsafe-eval'"),'PRODUCTION_CSP');await uiLogin(c,actors.officer);await patientPage(c);await c.page.getByRole('button',{name:'Keluar',exact:true}).click();await visible(c.page,c.page.getByRole('button',{name:'Masuk',exact:true}));check(!(await c.page.content()).includes(fixture.name),'LOGOUT_PROTECTED_CONTENT');await uiLogin(c,actors.officer);await patientPage(c);violations=await c.page.evaluate(()=>window.__e2eCsp);check(errors===0&&violations===0,'BROWSER_RUNTIME_OR_CSP_ERROR');});
 await scenario('B02',patientUiLink);
 await scenario('B03',async()=>{const c=await client();actors.uiPatient=c;await uiLogin(c,actors.patient);await c.page.goto(origin+'/portal');await visible(c.page,c.page.getByRole('heading',{name:'Portal Saya',exact:true}));await visible(c.page,c.page.getByText(fixture.name,{exact:true}));check(!(await c.page.content()).includes(fixture.identity),'PORTAL_BROWSER_PRIVACY');await patientUiRevoke();await observeSessionRefresh(c,'PATIENT',false);await request(actors.patient,'GET','/me/patient',undefined,403);await visible(c.page,c.page.getByRole('heading',{name:'Akses tidak diizinkan',exact:true}));check(!(await c.page.content()).includes(fixture.name),'PATIENT_PERMISSION_LOSS_CONTENT');await c.context.close();});
 await scenario('B04',async()=>{const c=actors.uiOfficer,p=c.page;await p.goto(origin+'/cases/'+fixture.case);await visible(p,p.getByRole('heading',{name:'Detail kasus',exact:true}));const section=p.getByRole('region',{name:'Pendamping kasus'});await section.getByRole('button',{name:'Tambah pendamping',exact:true}).click();const create=p.getByRole('dialog',{name:'Buat pendamping',exact:true});await create.getByLabel('Jenis pendamping').selectOption('COMPANION');await create.getByLabel('Nama pendamping').fill('E2E UI synthetic supporter');await create.getByRole('button',{name:'Simpan pendamping',exact:true}).click();await section.getByLabel('Email atau telepon login terverifikasi (persis)').fill(actors.supporter.email);await section.getByRole('button',{name:'Cari akun terverifikasi',exact:true}).click();await section.getByLabel(acknowledgement).check();await section.getByRole('button',{name:'Periksa tautan pendamping',exact:true}).click();const dialog=p.getByRole('dialog',{name:'Tautkan akun pendamping',exact:true});await visible(p,dialog);check(!roles((await request(actors.supporter,'GET','/me')).data).includes('TREATMENT_SUPPORTER'),'PRECONFIRM_SUPPORTER_ROLE');await dialog.getByRole('button',{name:'Konfirmasi tautkan akun pendamping',exact:true}).click();await visible(p,p.getByText('Tautan akun pendamping tersimpan.',{exact:true}));});
 await scenario('B05',async()=>{const c=await client();actors.uiSupporter=c;await uiLogin(c,actors.supporter);await c.page.goto(origin+'/supporting-cases');current.lastStep='UI_SUPPORTER_WAIT_ROSTER';await visible(c.page,c.page.getByRole('heading',{name:'Pendampingan',exact:true}));await c.page.getByRole('link',{name:'Buka pendampingan 1',exact:true}).click();current.lastStep='UI_SUPPORTER_WAIT_DETAIL';await visible(c.page,c.page.getByRole('heading',{name:'Pendampingan kasus',exact:true}));current.lastStep='UI_SUPPORTER_WAIT_EMPTY_STATE';await visible(c.page,c.page.getByText('Belum ada catatan pengobatan untuk pendampingan ini.',{exact:true}));const p=actors.uiOfficer.page,s=p.getByRole('region',{name:'Pendamping kasus'});await s.getByRole('button',{name:'Lepas akun pendamping',exact:true}).click();const d=p.getByRole('dialog',{name:'Lepas akun pendamping',exact:true});await d.getByRole('button',{name:'Konfirmasi lepas akun pendamping',exact:true}).click();await visible(p,p.getByText('Tautan akun pendamping dilepas.',{exact:true}));await request(actors.supporter,'GET',`/me/supporting-cases/${fixture.case}/treatment`,undefined,403);await observeSessionRefresh(c,'TREATMENT_SUPPORTER',false);await visible(c.page,c.page.getByRole('heading',{name:'Akses tidak diizinkan',exact:true}));check(!(await c.page.content()).includes('Pendampingan kasus'),'SUPPORTER_PERMISSION_LOSS_CONTENT');await c.context.close();});
 await scenario('B06',async()=>{const c=actors.uiOfficer;await patientPage(c);current.lastStep='UI_PATIENT_OPEN_EDITOR';await c.page.getByRole('button',{name:'Ubah pasien',exact:true}).click();await c.page.getByLabel('Tempat lahir',{exact:true}).fill('E2E UI pending update');const currentState=await request(actors.officer,'GET',`/patients/${fixture.patient}`);await request(actors.officer,'PATCH',`/patients/${fixture.patient}`,{birthPlace:'E2E concurrent server update'},200,{headers:{'If-Match':currentState.etag}});let sent=0,status;c.page.on('request',r=>{if(r.method()==='PATCH'&&r.url()===origin+api+'/patients/'+fixture.patient)sent++;});c.page.on('response',r=>{if(r.request().method()==='PATCH'&&r.url()===origin+api+'/patients/'+fixture.patient)status=r.status();});current.lastStep='UI_STALE_SUBMIT';await c.page.getByRole('button',{name:'Simpan perubahan',exact:true}).click();current.lastStep='UI_STALE_WAIT_REVIEW';await visible(c.page,c.page.getByRole('button',{name:'Saya sudah meninjau data terbaru',exact:true}));await c.page.waitForTimeout(1500);check(sent===1&&status===409,'UI_STALE_REPLAY');check(await c.page.getByLabel('Tempat lahir',{exact:true}).inputValue()==='E2E UI pending update','UI_DIRTY_STATE_LOST');operation('PATCH','/patients/{id}',status,409);current.operations.push({method:'OBSERVE',contract:'UI mutation request count',expectedStatus:1,actualStatus:sent});});
 await scenario('B07',async()=>{const c=actors.uiOfficer;await c.page.getByRole('button',{name:'Keluar',exact:true}).click();await uiLogin(c,actors.lab);check(!(await c.page.content()).includes(fixture.name),'ACCOUNT_SWITCH_PROTECTED_CONTENT');await c.page.goto(origin+'/patients/'+fixture.patient);await visible(c.page,c.page.getByRole('heading',{name:'Akses tidak diizinkan',exact:true}));check(!(await c.page.content()).includes(fixture.name),'WRONG_ROLE_BROWSER_LEAK');await c.page.getByRole('button',{name:'Keluar',exact:true}).click();await uiLogin(c,actors.officer);});
 await scenario('B08',async()=>{const c=actors.uiOfficer;await patientPage(c);await request(actors.admin,'DELETE',`/admin/facilities/${fixture.facilityA}/users/${actors.officer.id}`);current.lastStep="UI_MEMBERSHIP_WAIT_SESSION_REFRESH";const refreshed=c.page.waitForResponse(r=>r.url()===origin+api+'/me'&&r.request().method()==='GET');await c.page.bringToFront();await c.page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));const refresh=await refreshed;check(refresh.status()===200&&(await refresh.json()).activeFacilities.length===0,'LIVE_MEMBERSHIP_REFRESH');operation('UI_REFRESH','/me',refresh.status(),200);await request(actors.officer,'GET',`/patients/${fixture.patient}`,undefined,403);await visible(c.page,c.page.getByRole('heading',{name:'Akses tidak diizinkan',exact:true}));check(!(await c.page.content()).includes(fixture.name),'LIVE_MEMBERSHIP_LOSS_CONTENT');});
}
try{await main();const counts=Object.fromEntries(['PASS','FAIL','BLOCKED','NOT RUN'].map(s=>[s,results.filter(x=>x.status===s).length]));console.log(JSON.stringify({smoke:'complete',counts,workers:1,mutationRetries:0}));if(counts.FAIL||counts.BLOCKED)process.exitCode=3;}
catch(error){for(const r of results.filter(r=>r.status==='NOT RUN')){r.actual=stage==='preflight'?'Mandatory preflight did not pass':'Prerequisite scenario failed';r.status=stage==='preflight'?'NOT RUN':'BLOCKED';}save();console.log(JSON.stringify({smoke:'stopped',stage,classification:safe(error.message)}));process.exitCode=3;}
finally{for(const c of contexts)await c.close();if(browser)await browser.close();}
