"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useSession } from "@/lib/auth/session";
import { Button } from "@/components/ui/button";
import { QueryState } from "@/features/clinical-intake/components/query-state";
import { DisplayFields } from "@/features/clinical-intake/components/record-display";
import { treatmentQueries } from "../queries";
import { canTreatment } from "../permissions";
import { canMonitoring } from "@/features/monitoring/permissions";
import { DoseEvidence } from "./dose-evidence";
import { TreatmentEditor,type Editor } from "./treatment-editor";
export function TreatmentDetail({id}:{id:string}){
 const {user}=useSession(),query=useQuery(treatmentQueries.detail(user!.id,id)),refs=useQuery(treatmentQueries.references(user!.id)),t=query.data?.data,context=useQuery({...treatmentQueries.caseContext(user!.id,t?.caseId??""),enabled:t?.status==="ACTIVE"&&canTreatment(user,"CASE_READ","OUTCOME_READ","OUTCOME_WRITE")});
 const [editor,setEditor]=useState<Editor|null>(null),[saved,setSaved]=useState(false);if(!t)return <QueryState query={query}/>;
 const ref=refs.data?.data,active=t.status==="ACTIVE",allow=!query.isError&&!query.isFetching,label=(code:string)=>ref?.treatmentStatuses.find(o=>o.code===code)?.name??code,select=(e:Editor)=>{setSaved(false);setEditor(e);};
 return <div className="space-y-5"><h1 className="text-2xl font-semibold">Detail pengobatan</h1><section aria-label="Ringkasan pengobatan" className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">{t.patient.displayName}</h2><p>{t.facility.name} · {t.regimen?.name??"Paduan tidak tersedia"} · {label(t.status)}</p><p>Mulai: {t.startDate} · Akhir rencana: {t.plannedEndDate??"—"} · Akhir aktual: {t.actualEndDate??"—"}</p>{canTreatment(user,"CASE_READ")&&<Link href={`/cases/${t.caseId}`} className="text-primary underline">Buka kasus</Link>} <Link href={`/cases/${t.caseId}/treatments`} className="text-primary underline">Episode pengobatan kasus</Link></section>
 {canMonitoring(user,"TREATMENT_READ","MONITORING_READ")&&<Link className="text-primary underline" href={`/treatments/${id}/monitoring`}>Pemantauan</Link>}
 <Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Muat ulang pengobatan</Button>{query.isError&&<QueryState query={query}/>} {refs.isError&&<QueryState query={refs}/>} {context.isError&&<QueryState query={context}/>}
 <section aria-label="Metadata pengobatan" className="space-y-3"><h2 className="font-semibold">Metadata pengobatan</h2><DisplayFields values={[["Berat awal (kg)",t.initialWeightKg],["Bentuk OAT",t.oatForm],["Sumber obat",t.drugSource],["Awal intensif",t.intensiveStartDate],["Akhir intensif",t.intensiveEndDate],["Awal lanjutan",t.continuationStartDate],["Akhir lanjutan",t.continuationEndDate],["Deskripsi paduan",t.regimenDescription],["Catatan",t.notes]]}/></section>
 <section aria-label="Obat pengobatan" className="space-y-3"><h2 className="font-semibold">Obat pengobatan</h2>{t.drugs.map(d=><article key={d.id} className="space-y-2 rounded-xl border bg-white p-4"><h3 className="font-semibold">{d.drugName}</h3><p>{d.treatmentPhase??"—"} · {d.doseValue??"—"} {d.doseUnit??""} · Frekuensi per minggu: {d.frequencyPerWeek??"—"}</p><p>{d.startDate} – {d.endDate??"—"} · Batch: {d.batchNumber??"—"} · Sumber: {d.drugSource??"—"}</p><p className="whitespace-pre-wrap break-words">{d.notes??"—"}</p></article>)}</section>
 <div className="flex flex-wrap gap-3">{active&&canTreatment(user,"TREATMENT_WRITE")&&<Button disabled={!allow||!!editor||!query.data?.etag} onClick={()=>select({kind:"metadata"})}>Ubah metadata</Button>}{active&&canTreatment(user,"ADHERENCE_RECORD")&&<Button disabled={!allow||!!editor||!ref||refs.isError} onClick={()=>select({kind:"dose"})}>Catat bukti dosis</Button>}{active&&canTreatment(user,"FOLLOW_UP_WRITE")&&<Button disabled={!allow||!!editor||!query.data?.etag} onClick={()=>select({kind:"schedule"})}>Jadwalkan tindak lanjut</Button>}{active&&canTreatment(user,"ADVERSE_EVENT_WRITE")&&<Button disabled={!allow||!!editor} onClick={()=>select({kind:"adverse"})}>Catat kejadian tidak diinginkan</Button>}</div>
 {canTreatment(user,"ADHERENCE_READ")&&<DoseEvidence treatment={t} references={ref}/>}
 {canTreatment(user,"FOLLOW_UP_READ")&&<section aria-label="Tindak lanjut" className="space-y-3"><h2 className="font-semibold">Tindak lanjut</h2>{!t.followUps.length&&<p>Belum ada tindak lanjut.</p>}{t.followUps.map((f,i)=><article key={f.id} className="space-y-2 rounded-xl border bg-white p-4"><h3>{f.followUpType}</h3><p>{ref?.followUpStatuses.find(o=>o.code===f.status)?.name??f.status} · {f.facility?.name??"—"}</p><p>Jadwal: {new Date(f.scheduledAt).toLocaleString()} · Selesai: {f.completedAt?new Date(f.completedAt).toLocaleString():"—"}</p><DisplayFields values={[["Berat (kg)",f.weightKg],["Gejala",f.symptomSummary],["Penilaian kepatuhan",f.adherenceAssessment],["Catatan",f.notes]]}/>{active&&f.status==="SCHEDULED"&&canTreatment(user,"FOLLOW_UP_WRITE")&&user!.activeFacilities.some(scope=>scope.id===f.facility?.id)&&<Button disabled={!allow||!!editor} onClick={()=>select({kind:"complete",id:f.id})}>Selesaikan tindak lanjut {i+1}</Button>}</article>)}</section>}
 {canTreatment(user,"ADVERSE_EVENT_READ")&&<section aria-label="Kejadian tidak diinginkan" className="space-y-3"><h2 className="font-semibold">Kejadian tidak diinginkan</h2>{!t.adverseEvents.length&&<p>Belum ada kejadian tercatat.</p>}{t.adverseEvents.map((a,i)=><article key={a.id} className="space-y-2 rounded-xl border bg-white p-4"><h3>{a.eventType}</h3><p>Serius: {a.serious?"Ya":"Tidak"} · Dilaporkan: {new Date(a.reportedAt).toLocaleString()}</p><DisplayFields values={[["Tingkat keparahan",a.severity],["Awal",a.startedAt],["Akhir",a.endedAt],["Deskripsi",a.description],["Tindakan",a.actionTaken],["Hasil kejadian",a.outcome]]}/>{canTreatment(user,"ADVERSE_EVENT_WRITE")&&<Button disabled={!allow||!!editor} onClick={()=>select({kind:"updateAdverse",id:a.id})}>Ubah kejadian {i+1}</Button>}</article>)}</section>}
 {canTreatment(user,"OUTCOME_READ")&&<section aria-label="Hasil akhir" className="space-y-3"><h2 className="font-semibold">Hasil akhir</h2>{t.outcome?<DisplayFields values={[["Hasil akhir",t.outcome.outcomeName],["Tanggal",t.outcome.outcomeDate],["Catatan",t.outcome.notes]]}/>:<><p>Belum ada hasil akhir tercatat.</p>{active&&context.data?.data.status==="ACTIVE"&&canTreatment(user,"OUTCOME_WRITE")&&<Button disabled={!allow||!!editor||!query.data?.etag||!ref||refs.isError||context.isError||context.isFetching} onClick={()=>select({kind:"outcome"})}>Catat hasil akhir</Button>}</>}</section>}
 {canTreatment(user,"LAB_REQUEST_READ")&&<section aria-label="Laboratorium tindak lanjut" className="space-y-3"><h2 className="font-semibold">Laboratorium tindak lanjut</h2>{t.followUpLabRequests.map((r,i)=><p key={r.id}><Link className="text-primary underline" href={`/laboratory/requests/${r.id}`}>Permintaan {i+1}</Link> · {r.status}</p>)}</section>}
 {saved&&<p role="status">Perubahan tersimpan. Data pengobatan dimuat ulang.</p>}{editor&&<section aria-label="Formulir tindakan"><TreatmentEditor key={editor.kind+("id"in editor?editor.id:"")} editor={editor} treatment={t} etag={query.data?.etag} references={refs.isError?undefined:ref} caseActive={!context.isError&&!context.isFetching&&context.data?.data.status==="ACTIVE"} available={allow} onSuccess={()=>{setSaved(true);setEditor(null);}} onClose={()=>setEditor(null)}/></section>}
 </div>;
}
