"use client";
import { useId } from "react";
import { useFormContext,useFieldArray } from "react-hook-form";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { CheckField } from "@/features/clinical-intake/forms/fields";
import type { References } from "../types";
import { browserTimezone } from "../time";
import { drugValues } from "./values";
export function TreatmentField({name,label,type="text",options,required=false,multiline=false}:{name:string;label:string;type?:string;options?:{code:string;name:string}[];required?:boolean;multiline?:boolean}){
 const id=useId(),form=useFormContext(),error=form.getFieldState(name,form.formState).error;
 const props={id,...form.register(name),"aria-invalid":!!error,"aria-describedby":error?`${id}-error`:undefined};const style="min-h-11 w-full rounded-lg border bg-white px-3 py-2 text-sm";
 return <div className="space-y-2"><Label htmlFor={id}>{label}{required?" *":""}</Label>{options?<select {...props} className={style}><option value="">{required?"Pilih…":"Belum diisi / hapus"}</option>{options.map(o=><option key={o.code} value={o.code}>{o.name}</option>)}</select>:multiline?<textarea {...props} autoComplete="off" rows={3} className={style}/>:<Input {...props} autoComplete="off" type={type==="decimal"?"text":type} inputMode={type==="decimal"?"decimal":undefined} step={type==="datetime-local"?"0.001":undefined}/>}{error?.message&&<p id={`${id}-error`} role="alert" className="text-destructive text-sm">{error.message}</p>}{type==="datetime-local"&&<p className="text-xs">Zona waktu browser: {browserTimezone()}. Zona fasilitas dapat berbeda.</p>}</div>;
}
export function MetadataFields(){return <div className="grid gap-5 sm:grid-cols-2"><TreatmentField name="plannedEndDate" label="Tanggal akhir rencana" type="date"/><TreatmentField name="initialWeightKg" label="Berat awal (kg)" type="decimal"/><TreatmentField name="oatForm" label="Bentuk OAT"/><TreatmentField name="drugSource" label="Sumber obat"/>{[["intensiveStartDate","Awal fase intensif"],["intensiveEndDate","Akhir fase intensif"],["continuationStartDate","Awal fase lanjutan"],["continuationEndDate","Akhir fase lanjutan"]].map(([name,label])=><TreatmentField key={name} name={name} label={label} type="date"/>)}<TreatmentField name="regimenDescription" label="Deskripsi paduan" multiline/><TreatmentField name="notes" label="Catatan pengobatan" multiline/></div>;}
export function StartFields({references,category}:{references:References;category:string}){
 const {control}=useFormContext(),rows=useFieldArray({control,name:"drugs"});
 return <><p>TBCall tidak menyusun paduan atau dosis secara otomatis. Isi obat sesuai keputusan klinis yang telah ditetapkan.</p><TreatmentField name="regimenCode" label="Paduan pengobatan" required options={references.regimens.filter(r=>r.caseCategoryCode===category)}/><TreatmentField name="startDate" label="Tanggal mulai pengobatan" type="date" required/><MetadataFields/>
 <section className="space-y-4" aria-label="Obat yang dipilih"><h2 className="font-semibold">Obat yang dipilih</h2><p>Isi 1–20 obat secara eksplisit. Sekurangnya satu baris obat diperlukan.</p>{rows.fields.map((row,i)=><fieldset key={row.id} className="rounded-lg border p-4 space-y-4"><legend>Obat nomor {i+1}</legend><div className="grid gap-4 sm:grid-cols-2"><TreatmentField name={`drugs.${i}.drugCode`} label={`Obat ${i+1}`} required options={references.drugs}/><TreatmentField name={`drugs.${i}.treatmentPhase`} label={`Fase obat ${i+1}`}/><TreatmentField name={`drugs.${i}.doseValue`} label={`Dosis obat ${i+1}`} type="decimal"/><TreatmentField name={`drugs.${i}.doseUnit`} label={`Satuan dosis ${i+1}`}/><TreatmentField name={`drugs.${i}.frequencyPerWeek`} label={`Frekuensi per minggu ${i+1}`}/><TreatmentField name={`drugs.${i}.startDate`} label={`Tanggal awal obat ${i+1}`} type="date" required/><TreatmentField name={`drugs.${i}.endDate`} label={`Tanggal akhir obat ${i+1}`} type="date"/><TreatmentField name={`drugs.${i}.batchNumber`} label={`Nomor batch ${i+1}`}/><TreatmentField name={`drugs.${i}.drugSource`} label={`Sumber obat ${i+1}`}/><TreatmentField name={`drugs.${i}.notes`} label={`Catatan obat ${i+1}`} multiline/></div><Button type="button" variant="outline" disabled={rows.fields.length===1} onClick={()=>rows.remove(i)} aria-label={`Hapus obat ${i+1}`}>Hapus obat {i+1}</Button></fieldset>)}<Button type="button" disabled={rows.fields.length>=20} onClick={()=>rows.append(drugValues())}>Tambah obat</Button></section></>;
}
export function DoseFields({references}:{references:References}){return <><TreatmentField name="scheduledDate" label="Tanggal bukti dosis" type="date" required/><TreatmentField name="status" label="Status bukti" options={references.staffDoseStatuses} required/><TreatmentField name="administrationMode" label="Cara pemberian" options={references.administrationModes}/><TreatmentField name="notes" label="Catatan bukti dosis" multiline/></>;}
export function ScheduleFields({facilities}:{facilities:{id:string;name:string}[]}){return <><TreatmentField name="followUpType" label="Jenis tindak lanjut" required/><TreatmentField name="scheduledAt" label="Waktu jadwal" type="datetime-local" required/><TreatmentField name="facilityId" label="Fasilitas tindak lanjut (kosong: fasilitas pengobatan)" options={facilities.map(f=>({code:f.id,name:f.name}))}/><TreatmentField name="notes" label="Catatan jadwal" multiline/></>;}
export function CompleteFields(){return <><TreatmentField name="completedAt" label="Waktu selesai" type="datetime-local" required/><TreatmentField name="weightKg" label="Berat (kg)" type="decimal"/><TreatmentField name="symptomSummary" label="Ringkasan gejala" multiline/><TreatmentField name="adherenceAssessment" label="Penilaian kepatuhan"/><TreatmentField name="notes" label="Catatan penyelesaian" multiline/></>;}
export function AdverseFields({editing=false}:{editing?:boolean}){return <>{!editing&&<TreatmentField name="eventType" label="Jenis kejadian" required/>}<TreatmentField name="severity" label="Tingkat keparahan"/><CheckField name="serious" label="Kejadian serius"/><TreatmentField name="startedAt" label="Waktu awal kejadian" type="datetime-local"/><TreatmentField name="endedAt" label="Waktu akhir kejadian" type="datetime-local"/><TreatmentField name="description" label="Deskripsi kejadian" multiline/><TreatmentField name="actionTaken" label="Tindakan yang dicatat" multiline/><TreatmentField name="outcome" label="Hasil kejadian" multiline/></>;}
export function OutcomeFields({references}:{references:References}){return <><p>Pencatatan hasil akhir akan menutup episode pengobatan dan kasus ini.</p><TreatmentField name="outcomeCode" label="Kode hasil akhir" required options={references.outcomeCodes}/><TreatmentField name="outcomeDate" label="Tanggal hasil akhir" type="date" required/><TreatmentField name="notes" label="Catatan hasil akhir" multiline/><CheckField name="confirmed" label="Saya mengonfirmasi penutupan episode pengobatan dan kasus ini"/></>;}
