import { act, fireEvent, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { ME_QUERY_KEY } from "@/lib/auth/session";
import * as f from "./account-linking-fixtures";
import { backend, renderLinking, acknowledge, failure, tagged, client } from "./account-linking-harness";
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn(), replace: vi.fn() }), usePathname: () => "/patients" }));
const writes = (calls: ReturnType<typeof backend>["calls"]) => calls.filter(c => c.options.method !== "GET" && !c.url.endsWith("/resolve-user"));
it("never searches on typing and requires unchecked acknowledgement", async () => {
    const { calls } = backend();
    await renderLinking("patient");
    const input = await screen.findByLabelText("Email atau telepon login terverifikasi (persis)");
    fireEvent.change(input, { target: { value: "exact@example.test" } });
    expect(calls.some(c => c.url.endsWith("/resolve-user"))).toBe(false);
    fireEvent.click(screen.getByRole("button", { name: "Cari akun terverifikasi" }));
    await screen.findByText(/Akun tujuan:/);
    expect(input).toHaveValue("");
    expect(screen.getByRole("checkbox")).not.toBeChecked();
    expect(screen.getByRole("button", { name: "Periksa tautan pasien" })).toBeDisabled();
});
it.each(["absent", "PENDING", "REVOKED"])("links using authoritative %s pair precondition", async (status) => {
    const { calls } = backend(f.actor, c => c.url.includes("/precondition?") ? status === "absent" ? Response.json({ ...f.pairState, pair: null }) : tagged({ ...f.pairState, pair: { ...f.pairState.pair, verificationStatus: status } }, '"13"') : undefined);
    await renderLinking("patient");
    await acknowledge();
    fireEvent.click(screen.getByRole("button", { name: "Periksa tautan pasien" }));
    fireEvent.click(await screen.findByRole("button", { name: "Konfirmasi tautkan akun pasien" }));
    await screen.findByText("Tautan akun pasien tersimpan.");
    const write = writes(calls)[0];
    expect(write.body).toEqual({ userId: f.userId });
    expect(new Headers(write.options.headers).get("If-Match")).toBe(status === "absent" ? null : '"13"');
    expect(calls.filter(c => c.url.includes("/precondition?")).length).toBe(2);
    expect(screen.queryByRole("checkbox")).not.toBeInTheDocument();
});
it.each(["REJECTED", "VERIFIED"])("blocks a %s patient pair", async (status) => {
    const { calls } = backend(f.actor, c => c.url.includes("/precondition?") ? tagged({ ...f.pairState, pair: { ...f.pairState.pair, verificationStatus: status } }) : undefined);
    await renderLinking("patient");
    await acknowledge();
    fireEvent.click(screen.getByRole("button", { name: "Periksa tautan pasien" }));
    await screen.findByText(/Tautan pasangan/);
    expect(writes(calls)).toHaveLength(0);
    expect(screen.getByRole("button", { name: "Periksa tautan pasien" })).toBeDisabled();
});
it("blocks raced verified owner before patient link POST", async () => {
    let owner = false;
    const { calls } = backend(f.actor, c => c.options.method === "GET" && c.url.endsWith("/account-link") && owner ? tagged(f.patientState) : undefined);
    await renderLinking("patient");
    await acknowledge();
    owner = true;
    fireEvent.click(screen.getByRole("button", { name: "Periksa tautan pasien" }));
    await screen.findByText(/Pemilik akun terverifikasi/);
    expect(writes(calls)).toHaveLength(0);
});
it("revoke uses actual GET link ID and ETag and never legacy DELETE", async () => {
    const { calls, state } = backend();
    state.patient = f.patientState;
    await renderLinking("patient");
    fireEvent.click(await screen.findByRole("button", { name: "Cabut tautan pasien" }));
    expect(writes(calls)).toHaveLength(0);
    fireEvent.click(await screen.findByRole("button", { name: "Konfirmasi cabut tautan pasien" }));
    await screen.findByText("Tautan akun pasien dicabut.");
    const write = writes(calls)[0];
    expect(write.url).toBe(`/api/tbcall/v1/patients/${f.ids.patient}/account-links/${f.linkId}`);
    expect(new Headers(write.options.headers).get("If-Match")).toBe('"31"');
    expect(write.body).toBeNull();
});
it("equal-version replacement between review and revoke requires a new confirmation", async () => {
    const { calls, state } = backend();
    state.patient = f.patientState;
    await renderLinking("patient");
    fireEvent.click(await screen.findByRole("button", { name: "Cabut tautan pasien" }));
    await screen.findByRole("dialog");
    state.patient = { link: { ...f.link, id: f.supporterId, userId: f.ids.destination } };
    fireEvent.click(screen.getByRole("button", { name: "Konfirmasi cabut tautan pasien" }));
    await screen.findByText(/Data atau status tautan telah berubah/);
    expect(writes(calls)).toHaveLength(0);
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
});
it("stale revoke 409 re-reads current link and never replays", async () => {
    const { calls, state } = backend(f.actor, c => c.options.method === "DELETE" ? failure(409) : undefined);
    state.patient = f.patientState;
    await renderLinking("patient");
    fireEvent.click(await screen.findByRole("button", { name: "Cabut tautan pasien" }));
    fireEvent.click(await screen.findByRole("button", { name: "Konfirmasi cabut tautan pasien" }));
    await screen.findByText(/Data atau status tautan telah berubah/);
    expect(writes(calls)).toHaveLength(1);
    expect(calls.filter(c => c.url.endsWith("/account-link") && c.options.method === "GET").length).toBeGreaterThanOrEqual(4);
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
});
it.each([[404, "RESOURCE_NOT_FOUND", "Tidak ditemukan akun aktif"], [429, "ACCOUNT_RESOLUTION_LIMIT", "Batas pencarian akun"]])("resolver %i is safe and never retries", async (status, code, message) => {
    const { calls } = backend(f.actor, c => c.url.endsWith("/resolve-user") ? failure(status as number, code as string) : undefined);
    await renderLinking("patient");
    fireEvent.change(await screen.findByLabelText("Email atau telepon login terverifikasi (persis)"), { target: { value: "exact@example.test" } });
    fireEvent.click(screen.getByRole("button", { name: "Cari akun terverifikasi" }));
    await screen.findByText(new RegExp(message as string));
    expect(calls.filter(c => c.url.endsWith("/resolve-user"))).toHaveLength(1);
    expect(screen.queryByText(/PRIVATE RAW/)).not.toBeInTheDocument();
    expect(screen.getByLabelText("Email atau telepon login terverifikasi (persis)")).toHaveValue("");
});
it.each(["account", "roles", "permissions", "facilities"])("clears and suppresses late resolution after %s snapshot change", async (change) => {
    let complete!: (r: Response) => void;
    const { calls } = backend(f.actor, c => c.url.endsWith("/resolve-user") ? new Promise<Response>(r => { complete = r; }) : undefined);
    await renderLinking("patient");
    fireEvent.change(await screen.findByLabelText("Email atau telepon login terverifikasi (persis)"), { target: { value: "exact@example.test" } });
    fireEvent.click(screen.getByRole("button", { name: "Cari akun terverifikasi" }));
    await waitFor(() => expect(complete).toBeDefined());
    const next = { ...f.actor, ...(change === "account" ? { id: "other-actor" } : change === "roles" ? { roles: [...f.actor.roles, { code: "PROGRAM_MONITOR", name: "Monitor" }] } : change === "permissions" ? { permissions: [...f.actor.permissions, "EXTRA"] } : { activeFacilities: [{ id: f.ids.destination, name: "Other" }] }) };
    await act(async () => { client.setQueryData(ME_QUERY_KEY, next); complete(Response.json(f.candidate)); });
    expect(screen.queryByText(/Akun tujuan:/)).not.toBeInTheDocument();
    expect(calls.find(c => c.url.endsWith("/resolve-user"))!.options.signal?.aborted).toBe(true);
});
