import { fireEvent, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import * as f from "./account-linking-fixtures";
import { backend, renderLinking, selectSupporter, acknowledge, tagged, failure } from "./account-linking-harness";
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn(), replace: vi.fn() }), usePathname: () => "/cases" }));
it("lists and selects supporter detail separately from roster", async () => { const { calls } = backend(); await renderLinking("supporter"); await selectSupporter(); expect(calls.some(c => c.url.endsWith(`/supporters/${f.supporterId}`))).toBe(true); expect(screen.getByText("Belum ada akun tertaut.")).toBeInTheDocument(); });
it("link uses fresh detail GET ETag instead of numeric DTO version", async () => {
    const { calls } = backend(f.actor, c => c.options.method === "GET" && c.url.endsWith(`/supporters/${f.supporterId}`) ? tagged(f.detail, '"13"') : undefined);
    await renderLinking("supporter");
    await selectSupporter();
    await acknowledge();
    fireEvent.click(screen.getByRole("button", { name: "Periksa tautan pendamping" }));
    fireEvent.click(await screen.findByRole("button", { name: "Konfirmasi tautkan akun pendamping" }));
    await screen.findByText("Tautan akun pendamping tersimpan.");
    const post = calls.find(c => c.options.method === "POST" && c.url.endsWith("/account-link"))!;
    expect(post.body).toEqual({ userId: f.userId });
    expect(new Headers(post.options.headers).get("If-Match")).toBe('"13"');
    expect(calls.filter(c => c.url.endsWith(`/supporters/${f.supporterId}`)).length).toBeGreaterThanOrEqual(4);
});
it("replacement adds explicit warning and separate confirmation", async () => {
    const { calls, state } = backend();
    state.supporter = { ...f.detail, linkedUser: { userId: f.ids.destination, ...f.maskedAccount } };
    await renderLinking("supporter");
    await selectSupporter();
    await acknowledge();
    fireEvent.click(screen.getByRole("button", { name: "Periksa tautan pendamping" }));
    await screen.findByText(/Akun sebelumnya dapat kehilangan akses/);
    expect(calls.some(c => c.options.method === "POST" && c.url.endsWith("/account-link"))).toBe(false);
    expect(screen.getByRole("button", { name: "Konfirmasi ganti akun pendamping" })).toBeDisabled();
    fireEvent.click(screen.getByLabelText("Saya menyetujui penggantian akun pendamping ini."));
    fireEvent.click(screen.getByRole("button", { name: "Konfirmasi ganti akun pendamping" }));
    await screen.findByText("Tautan akun pendamping tersimpan.");
});
it.each(["TRANSFERRED", "COMPLETED", "CLOSED", "CANCELLED"])("%s case reads and unlinks without prospective controls", async (status) => {
    const { calls, state } = backend();
    state.supporter = { ...f.detail, linkedUser: { userId: f.userId, ...f.maskedAccount } };
    await renderLinking("supporter", status);
    await selectSupporter();
    expect(screen.queryByRole("button", { name: "Tambah pendamping" })).not.toBeInTheDocument();
    expect(screen.queryByLabelText("Email atau telepon login terverifikasi (persis)")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Lepas akun pendamping" }));
    fireEvent.click(await screen.findByRole("button", { name: "Konfirmasi lepas akun pendamping" }));
    await screen.findByText("Tautan akun pendamping dilepas.");
    expect(new Headers(calls.find(c => c.options.method === "DELETE")!.options.headers).get("If-Match")).toBe('"31"');
});
it("inactive supporter remains visible without resolve/link/unlink controls", async () => { const { state } = backend(); state.supporter = { ...f.detail, active: false }; state.page = { ...f.page, content: [{ ...f.summary, active: false }] }; await renderLinking("supporter"); await selectSupporter(); expect(screen.getByText("Pendamping tidak aktif; perubahan tautan tidak tersedia.")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Cari akun terverifikasi" })).not.toBeInTheDocument(); });
it("creates trimmed minimal record and selects authoritative GET detail", async () => {
    const { calls } = backend();
    await renderLinking("supporter");
    fireEvent.click(await screen.findByRole("button", { name: "Tambah pendamping" }));
    fireEvent.change(screen.getByLabelText("Nama pendamping"), { target: { value: "  Pendamping Baru  " } });
    fireEvent.change(screen.getByLabelText("Telepon kontak (opsional)"), { target: { value: "08123" } });
    fireEvent.click(screen.getByRole("button", { name: "Simpan pendamping" }));
    await screen.findByRole("heading", { name: "Detail pendamping" });
    const post = calls.find(c => c.options.method === "POST")!;
    expect(post.body).toEqual({ supporterType: "PMO", fullName: "Pendamping Baru", phone: "08123" });
    expect(new Headers(post.options.headers).has("If-Match")).toBe(false);
    expect(calls.some(c => c.options.method === "GET" && c.url.endsWith(`/supporters/${f.supporterId}`))).toBe(true);
});
it("source-authority creation conflict locks repeated creation across cancel/reopen", async () => {
    const { calls } = backend(f.actor, c => c.options.method === "POST" && c.url.endsWith("/supporters") ? failure(409, "SOURCE_AUTHORITY_CONFLICT") : undefined);
    await renderLinking("supporter");
    fireEvent.click(await screen.findByRole("button", { name: "Tambah pendamping" }));
    fireEvent.change(screen.getByLabelText("Nama pendamping"), { target: { value: "Pendamping Baru" } });
    fireEvent.click(screen.getByRole("button", { name: "Simpan pendamping" }));
    await screen.findByText(/Data ini hanya dapat dibaca/);
    expect(screen.getByRole("button", { name: "Simpan pendamping" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "Batal buat pendamping" }));
    expect(screen.getByRole("button", { name: "Tambah pendamping" })).toBeDisabled();
    expect(calls.filter(c => c.options.method === "POST")).toHaveLength(1);
});
it("uncertain creation requires roster check before another create", async () => {
    const { calls } = backend(f.actor, c => c.options.method === "POST" && c.url.endsWith("/supporters") ? Promise.reject(new TypeError("network interruption")) : undefined);
    await renderLinking("supporter");
    fireEvent.click(await screen.findByRole("button", { name: "Tambah pendamping" }));
    fireEvent.change(screen.getByLabelText("Nama pendamping"), { target: { value: "Pendamping Baru" } });
    fireEvent.click(screen.getByRole("button", { name: "Simpan pendamping" }));
    await screen.findByText(/Hasil pembuatan belum dapat dipastikan/);
    expect(calls.filter(c => c.options.method === "POST")).toHaveLength(1);
    expect(screen.getByRole("button", { name: "Simpan pendamping" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "Muat ulang daftar pendamping" }));
    await waitFor(() => expect(screen.getByRole("button", { name: "Simpan pendamping" })).not.toBeDisabled());
});
