import {expect,it} from "vitest";
import * as f from "./continuity-fixtures";
const modules=import.meta.glob("../features/continuity/**/*.ts");
async function load<T>(file:string):Promise<T>{const loader=modules[`../features/continuity/${file}.ts`];if(!loader)throw new Error(`Missing continuity module ${file}`);return await loader() as T;}
it.each(["preparation","referral","contact","investigation","tpt"] as const)("strict %s response rejects extra private enrichment",async name=>{const s=await load<typeof import("@/features/continuity/schemas")>("schemas");const schema={preparation:s.preparationSchema,referral:s.referralSchema,contact:s.contactSchema,investigation:s.investigationSchema,tpt:s.tptSchema}[name];expect(schema.safeParse(f[name]).success).toBe(true);expect(schema.safeParse({...f[name],patientNik:"private"}).success).toBe(false);});
it("TPT references reject null category/composition and permit empty live catalogs",async()=>{const s=await load<typeof import("@/features/continuity/schemas")>("schemas");expect(s.tptReferencesSchema.safeParse(f.tptReferences).success).toBe(true);for(const r of [{...f.tptReferences.preventiveRegimens[0],caseCategoryCode:null},{...f.tptReferences.preventiveRegimens[0],dose:"auto"}])expect(s.tptReferencesSchema.safeParse({...f.tptReferences,preventiveRegimens:[r]}).success).toBe(false);expect(s.tptReferencesSchema.safeParse({...f.tptReferences,preventiveRegimens:[]}).success).toBe(true);});
it("contact dirty patch omits masked unchanged phone and immutable fields",async()=>{const m=await load<typeof import("@/features/continuity/contacts/forms")>("contacts/forms");expect(m.contactValues(f.contact).phone).toBe("");expect(m.contactPatch({...m.contactValues(f.contact),fullName:" Name ",phone:""},{fullName:true,phone:true,linkedPatient:true,id:true})).toEqual({fullName:"Name",phone:null});expect(m.contactPatch(m.contactValues(f.contact),{address:true})).toEqual({address:f.contact.address});});
it("INTERNAL contact creation omits destination and outgoing requires explicit selection",async()=>{const m=await load<typeof import("@/features/continuity/contacts/forms")>("contacts/forms");const v={...m.contactValues(),fullName:"New",workflowType:"INTERNAL",destinationFacilityId:f.destination.id};expect(m.contactInput(v)).not.toHaveProperty("destinationFacilityId");expect(m.contactCreateSchema.safeParse({...v,workflowType:"OUTGOING_REFERRAL",destinationFacilityId:""}).success).toBe(false);});
it("explicit completion booleans are required and consistency alone is enforced",async()=>{const m=await load<typeof import("@/features/continuity/contacts/forms")>("contacts/forms");for(const v of [{},{activeTbExcluded:"",tptEligible:""},{activeTbExcluded:"false",tptEligible:"true"}])expect(m.completionSchema.safeParse({...m.completionValues(),...v}).success).toBe(false);expect(m.completionInput({...m.completionValues(),activeTbExcluded:"true",tptEligible:"true"})).toEqual({activeTbExcluded:true,tptEligible:true});});
it("TPT start requires explicit catalog or description with no default inference",async()=>{const m=await load<typeof import("@/features/continuity/tpt/forms")>("tpt/forms");const v={...m.tptValues(),startDate:"2026-09-01"};expect(v.regimenCode).toBe("");expect(v.durationValue).toBe("");expect(v.plannedEndDate).toBe("");expect(m.tptStartSchema.safeParse(v).success).toBe(false);expect(m.tptStartSchema.safeParse({...v,regimenDescription:"Explicit"}).success).toBe(true);expect(m.tptInput({...v,regimenDescription:"Explicit"})).toEqual({startDate:"2026-09-01",regimenDescription:"Explicit"});});
it("TPT dirty patches allow null clears but cannot erase sole individualized regimen",async()=>{const m=await load<typeof import("@/features/continuity/tpt/forms")>("tpt/forms");expect(m.tptPatch({...m.tptValues(f.tpt),notes:"",durationValue:"2"},{notes:true,durationValue:true,startDate:true,status:true})).toEqual({notes:null,durationValue:2});expect(m.tptEditSchema(f.tpt).safeParse({...m.tptValues(f.tpt),regimenDescription:""}).success).toBe(false);expect(m.tptEditSchema({...f.tpt,regimenCode:"SO"}).safeParse({...m.tptValues(f.tpt),regimenDescription:""}).success).toBe(true);});
it.each(["0","-1","1.5"])("TPT duration %s is invalid",async durationValue=>{const m=await load<typeof import("@/features/continuity/tpt/forms")>("tpt/forms");expect(m.tptStartSchema.safeParse({...m.tptValues(f.tpt),durationValue}).success).toBe(false);});
it("stop closure requires reason; all closures require confirmation",async()=>{const m=await load<typeof import("@/features/continuity/tpt/forms")>("tpt/forms");expect(m.closureSchema("stop").safeParse({...m.closureValues(),confirmed:true}).success).toBe(false);expect(m.closureSchema("complete").safeParse(m.closureValues()).success).toBe(false);expect(m.closureInput({...m.closureValues(),confirmed:true})).toEqual({});});
