import { screen, waitFor, fireEvent, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, it, vi } from "vitest";
import { backend, renderF4, routing, failure } from "./f4-harness";
import * as f from "./f4-fixtures";
vi.mock("next/navigation", () => ({ useRouter: () => routing, usePathname: () => "/integrations" }));
it("integration list shows metadata flag/configuration, counts, latest safe run and approved links", async () => {
    const calls = backend();
    await renderF4("integrations");
    await screen.findByText("UNCONFIGURED");
    expect(screen.getByText('Status "aktif" adalah metadata TBCall dan tidak berarti konektor sudah dikonfigurasi atau terhubung.')).toBeInTheDocument();
    expect(screen.getByText("PRIVATE_CURSOR")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Buka detail proses" })).toHaveAttribute("href", `/integrations/SITB/sync-runs/${f.runId}`);
    expect(calls.every(c => c.url.startsWith("/api/tbcall/v1/"))).toBe(true);
});
it.each([["Otoritas sumber", "/authorities"], ["Proses sinkronisasi", "/sync-runs"], ["Konflik", "/conflicts"]] as const)("%s uses a separate explicit read with no raw data or clinical links", async (label, path) => {
    const calls = backend();
    await renderF4("integration");
    await screen.findByText("PRIVATE_EXTERNAL");
    expect(calls.some(c => c.url.includes(path))).toBe(false);
    await userEvent.click(screen.getByRole("button", { name: label }));
    await waitFor(() => expect(calls.some(c => c.url.includes(path))).toBe(true));
    expect(screen.queryByRole("button", { name: /Resolve|Abaikan|Sinkronkan|Konfigurasi/ })).not.toBeInTheDocument();
    expect([...screen.getAllByRole("link")].every(link => !link.getAttribute("href")?.includes(f.targetId))).toBe(true);
    expect(location.search).toBe("");
});
it("integration sections keep independent pages in memory and never change history", async () => {
    const history = vi.spyOn(window.history, "pushState"), replace = vi.spyOn(window.history, "replaceState");
    const calls = backend(f.admin, c => c.url.includes("/external-identifiers") ? Response.json({ ...f.page(f.identifier), page: Number(new URL(c.url, "http://localhost").searchParams.get("page")), totalElements: 41 }) : undefined);
    await renderF4("integration");
    await screen.findByText("PRIVATE_EXTERNAL");
    await userEvent.click(screen.getByRole("button", { name: "Berikutnya" }));
    await screen.findByText("Halaman 2 · 41 data");
    await userEvent.click(screen.getByRole("button", { name: "Otoritas sumber" }));
    await screen.findByText("Halaman 1 · 1 data");
    await userEvent.click(screen.getByRole("button", { name: "Identitas eksternal" }));
    await screen.findByText("Halaman 2 · 41 data");
    expect(calls.some(c => c.url.includes("external-identifiers?page=1"))).toBe(true);
    expect(history).not.toHaveBeenCalled();
    expect(replace).not.toHaveBeenCalled();
});
it("run displays only approved item metadata and pages locally without N+1 clinical enrichment", async () => {
    const calls = backend(f.admin, c => c.url.includes("/sync-runs/") ? Response.json({ run: f.run, items: { ...f.page(f.item), page: Number(new URL(c.url, "http://localhost").searchParams.get("page")), totalElements: 21 } }) : undefined);
    await renderF4("run");
    await screen.findByText("PRIVATE_HASH");
    expect(screen.getByText("PRIVATE_LOCAL_HASH")).toBeInTheDocument();
    await userEvent.click(screen.getByRole("button", { name: "Berikutnya" }));
    await screen.findByText("Halaman 2 · 21 data");
    expect(calls.every(c => c.url.endsWith("/me") || c.url.includes(`/integrations/SITB/sync-runs/${f.runId}`))).toBe(true);
    expect(location.search).toBe("");
});
it.each(["integrations", "integration", "run"] as const)("%s has no automatic focus/reconnect refetch or mutations", async (page) => {
    const calls = backend();
    await renderF4(page);
    await screen.findByText("UNCONFIGURED").catch(() => screen.findByText("PRIVATE_HASH"));
    const count = calls.length;
    fireEvent(window, new Event("focus"));
    fireEvent(window, new Event("online"));
    await new Promise(r => setTimeout(r, 60));
    expect(calls).toHaveLength(count);
    await userEvent.click(screen.getAllByRole("button", { name: "Muat ulang" })[0]);
    await waitFor(() => expect(calls.length).toBeGreaterThan(count));
    expect(calls.every(c => c.options.method === "GET")).toBe(true);
});
it.each([401, 403, 409, 503])("integration %s errors never render raw problem prose or payload", async (status) => { backend(f.admin, c => c.url.includes("/integrations") ? failure(status) : undefined); await renderF4("integrations"); await waitFor(() => expect(screen.queryByText("Memuat data…")).not.toBeInTheDocument()); expect(screen.queryByText(/PRIVATE RAW/)).not.toBeInTheDocument(); });
it("exact identity and integration content never enter storage, console, titles or browser navigation", async () => {
    const storage = vi.spyOn(Storage.prototype, "setItem"), history = vi.spyOn(window.history, "pushState"), replace = vi.spyOn(window.history, "replaceState"), log = vi.spyOn(console, "log"), warn = vi.spyOn(console, "warn"), error = vi.spyOn(console, "error"), db = vi.fn();
    vi.stubGlobal("indexedDB", { open: db });
    const calls = backend();
    const users = await renderF4("users");
    await userEvent.type(await screen.findByLabelText("Email atau nomor telepon tepat"), "SECRET_EXACT@example.test");
    await userEvent.click(screen.getByRole("button", { name: "Cari pengguna tepat" }));
    await screen.findByText("t***@example.test");
    expect(calls.find(c => c.url.includes("/users/lookup"))?.url).toContain("SECRET_EXACT%40example.test");
    expect(within(screen.getByRole("banner")).queryByText("t***@example.test")).not.toBeInTheDocument();
    users.unmount();
    await renderF4("run");
    await screen.findByText("PRIVATE_HASH");
    expect(screen.getAllByRole("link").every(link => !/(PRIVATE_|SECRET_EXACT)/.test(link.getAttribute("href") ?? ""))).toBe(true);
    expect(document.title).not.toMatch(/PRIVATE_|SECRET_EXACT/);
    expect(location.href).not.toMatch(/PRIVATE_|SECRET_EXACT/);
    [storage, history, replace, log, warn, error, db].forEach(spy => expect(spy).not.toHaveBeenCalled());
});
