import { officer, ids, facility } from "./clinical-fixtures";
export const treatmentIds = { treatment: "77777777-7777-4777-8777-777777777777", drug: "88888888-8888-4888-8888-888888888888", follow: "99999999-9999-4999-8999-999999999999", adverse: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", dose: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb" };
export const treatmentOfficer = { ...officer, permissions: [...officer.permissions, "TREATMENT_READ", "TREATMENT_WRITE", "ADHERENCE_READ", "ADHERENCE_RECORD", "FOLLOW_UP_READ", "FOLLOW_UP_WRITE", "ADVERSE_EVENT_READ", "ADVERSE_EVENT_WRITE", "OUTCOME_READ", "OUTCOME_WRITE", "LAB_REQUEST_READ"] };
const options = (rows: string[]) => rows.map(v => { const [code,name] = v.split("|"); return { code, name }; });
export const treatmentReferences = {
  regimens: [{code:"SO",name:"Paduan SO",caseCategoryCode:"TB_SO"},{code:"RO",name:"Paduan RO",caseCategoryCode:"TB_RO"}],
  drugs: [{code:"H",name:"Nama obat kini"},{code:"R",name:"Obat kedua"}], outcomeCodes: [{code:"SEMBUH",name:"Sembuh"}],
  treatmentStatuses: options(["PLANNED|Direncanakan","ACTIVE|Aktif","PAUSED|Dijeda","TRANSFERRED|Dialihkan","COMPLETED|Selesai","STOPPED|Dihentikan","CANCELLED|Dibatalkan"]),
  staffDoseStatuses: options(["TAKEN_OBSERVED|Diminum terobservasi","TAKEN_SELF_REPORTED|Diminum berdasarkan laporan","DISPENSED_HOME|Obat dibawa pulang","MISSED|Tidak diminum","UNKNOWN|Tidak diketahui"]),
  administrationModes: options(["DIRECTLY_OBSERVED|Diawasi langsung","SELF_ADMINISTERED|Diminum mandiri","OTHER|Lainnya"]), followUpStatuses: options(["SCHEDULED|Terjadwal","COMPLETED|Selesai"]),
};
export const treatmentDose = {id:treatmentIds.dose,scheduledDate:"2026-09-04",recordedAt:"2026-09-04T12:00:00+07:00",status:"TAKEN_OBSERVED" as const,administrationMode:"DIRECTLY_OBSERVED",source:"HEALTH_WORKER",recordedByUserId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",notes:"Private dose note"};
export const treatmentFollow = {id:treatmentIds.follow,version:8,treatmentId:treatmentIds.treatment,followUpType:"Kunjungan",scheduledAt:"2026-09-05T12:00:00+07:00",completedAt:null,facility,healthWorkerId:null,status:"SCHEDULED" as const,weightKg:null,symptomSummary:null,adherenceAssessment:null,notes:null};
export const treatmentAdverse = {id:treatmentIds.adverse,version:9,treatmentId:treatmentIds.treatment,reportedAt:"2026-09-05T12:00:00+07:00",eventType:"Keluhan dicatat",severity:null,serious:false,startedAt:"2026-09-05T12:00:00.123456+07:00",endedAt:null,description:"Private adverse description",actionTaken:null,outcome:null};
export const treatmentOutcome = {id:treatmentIds.adverse,outcomeCode:"SEMBUH",outcomeName:"Sembuh",outcomeDate:"2026-09-10",notes:null};
export const treatmentDetail = {id:treatmentIds.treatment,version:3,caseId:ids.tbCase,patient:{id:ids.patient,displayName:"Pasien Pengobatan"},facility,regimen:{code:"SO",name:"Paduan SO"},status:"ACTIVE" as const,startDate:"2026-09-04",plannedEndDate:null,actualEndDate:null,initialWeightKg:55.5,oatForm:null,drugSource:null,intensiveStartDate:null,intensiveEndDate:null,continuationStartDate:null,continuationEndDate:null,regimenDescription:null,notes:"Private treatment note",drugs:[{id:treatmentIds.drug,drugCode:"H",drugName:"Nama snapshot historis",treatmentPhase:null,doseValue:null,doseUnit:null,frequencyPerWeek:null,startDate:"2026-09-04",endDate:null,batchNumber:null,drugSource:null,notes:null}],adherenceSummary:{totalReports:1,reportsByStatus:{TAKEN_OBSERVED:1}},recentDoseEvents:[treatmentDose],followUps:[treatmentFollow],adverseEvents:[treatmentAdverse],outcome:null,followUpLabRequests:[{id:ids.diagnosis,status:"REQUESTED"}]};
