import { screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, it, vi } from "vitest";
import { ids } from "./clinical-fixtures";
import { treatmentIds, treatmentOfficer, treatmentDetail, treatmentFollow, treatmentOutcome } from "./treatment-fixtures";
import { treatmentBackend, renderTreatment, routing, failure } from "./treatment-harness";
vi.mock("next/navigation",()=>({useRouter:()=>routing,usePathname:()=>"/treatments/id"}));
const detail=()=>renderTreatment("detail",treatmentIds.treatment);
const click=async(name:string)=>userEvent.click(await screen.findByRole("button",{name}));
it("episode route uses contextual case/ref data and never constructs regimen drugs",async()=>{
 const calls=treatmentBackend();await renderTreatment("episodes",ids.tbCase);await click("Mulai pengobatan");
 expect(screen.getByText(/TBCall tidak menyusun paduan/)).toBeInTheDocument();expect(screen.queryByRole("option",{name:"Paduan RO"})).not.toBeInTheDocument();
 await userEvent.selectOptions(screen.getByLabelText(/Paduan pengobatan/),"SO");expect(screen.getByLabelText(/Obat 1/)).toHaveValue("");expect(calls.some(c=>c.url.includes("/patients/"))).toBe(false);
});
it.each(["PLANNED","ACTIVE","PAUSED"])("existing %s episode suppresses start",async status=>{treatmentBackend(c=>c.url.includes("/cases/")&&c.url.endsWith("/treatments")?Response.json([{...treatmentDetail,status}]):undefined);await renderTreatment("episodes",ids.tbCase);await screen.findByText("Paduan SO");expect(screen.queryByRole("button",{name:"Mulai pengobatan"})).not.toBeInTheDocument();});
it("explicit start sends user-selected drug lines without ETag or computed composition and navigates",async()=>{
 const calls=treatmentBackend();await renderTreatment("episodes",ids.tbCase);await click("Mulai pengobatan");await userEvent.selectOptions(screen.getByLabelText(/Paduan pengobatan/),"SO");await userEvent.type(screen.getByLabelText("Tanggal mulai pengobatan *"),"2026-09-04");await userEvent.selectOptions(screen.getByLabelText(/Obat 1/),"H");await userEvent.type(screen.getByLabelText("Tanggal awal obat 1 *"),"2026-09-04");await click("Simpan pengobatan");await waitFor(()=>expect(routing.push).toHaveBeenCalledWith(`/treatments/${treatmentIds.treatment}`));const c=calls.find(c=>c.options.method==="POST")!;expect(new Headers(c.options.headers).has("If-Match")).toBe(false);expect(c.body).not.toHaveProperty("status");expect(c.body?.drugs).toEqual([expect.objectContaining({drugCode:"H",doseValue:null,frequencyPerWeek:null,treatmentPhase:null})]);
});
it("snapshot is displayed, metadata patch uses actual ETag and dirty-only null clear",async()=>{
 const calls=treatmentBackend();await detail();await screen.findByText("Nama snapshot historis");await click("Ubah metadata");await userEvent.clear(screen.getByLabelText("Catatan pengobatan"));await click("Simpan metadata");await screen.findByText(/Perubahan tersimpan/);const c=calls.find(c=>c.options.method==="PATCH")!;expect(c.body).toEqual({notes:null});expect(new Headers(c.options.headers).get("If-Match")).toBe('"actual-treatment-tag"');
});
it.each(["TREATMENT_WRITE","ADHERENCE_RECORD","FOLLOW_UP_WRITE","ADVERSE_EVENT_WRITE","OUTCOME_WRITE"])("action independently requires %s",async permission=>{
 const actor={...treatmentOfficer,permissions:treatmentOfficer.permissions.filter(p=>p!==permission)};treatmentBackend(undefined,actor);await detail();await screen.findByText("Pasien Pengobatan");const labels:Record<string,string>={TREATMENT_WRITE:"Ubah metadata",ADHERENCE_RECORD:"Catat bukti dosis",FOLLOW_UP_WRITE:"Jadwalkan tindak lanjut",ADVERSE_EVENT_WRITE:"Catat kejadian tidak diinginkan",OUTCOME_WRITE:"Catat hasil akhir"};expect(screen.queryByRole("button",{name:labels[permission]})).not.toBeInTheDocument();
});
it.each(["ADHERENCE_READ","FOLLOW_UP_READ","ADVERSE_EVENT_READ","OUTCOME_READ"])("read section independently requires %s",async permission=>{
 treatmentBackend(c=>c.url.endsWith(treatmentIds.treatment)?Response.json({...treatmentDetail,outcome:treatmentOutcome},{headers:{ETag:'"server"'}}):undefined,{...treatmentOfficer,permissions:treatmentOfficer.permissions.filter(p=>p!==permission)});await detail();await screen.findByText("Pasien Pengobatan");const headings:Record<string,string>={ADHERENCE_READ:"Bukti dosis",FOLLOW_UP_READ:"Tindak lanjut",ADVERSE_EVENT_READ:"Kejadian tidak diinginkan",OUTCOME_READ:"Hasil akhir"};expect(screen.queryByRole("heading",{name:headings[permission]})).not.toBeInTheDocument();
});
it.each(["LAB_STAFF","SYSTEM_ADMIN","FACILITY_ADMIN","PROGRAM_MONITOR","PATIENT","TREATMENT_SUPPORTER"])("%s with artificial permissions cannot enter",async role=>{const calls=treatmentBackend(undefined,{...treatmentOfficer,roles:[{code:role,name:role}]});await detail();await screen.findByRole("heading",{name:"Akses tidak diizinkan"});expect(calls).toHaveLength(1);});
it("scheduling uses treatment ETag, assigned-facility choices and refetches advanced treatment version",async()=>{
 let scheduled=false;const calls=treatmentBackend(c=>{if(c.url.endsWith("/follow-ups")&&c.options.method==="POST"){scheduled=true;return Response.json(treatmentFollow,{headers:{ETag:'"child-only-tag"'}});}if(c.url.endsWith(treatmentIds.treatment))return Response.json({...treatmentDetail,version:scheduled?4:3},{headers:{ETag:scheduled?'"advanced-treatment"':'"actual-treatment-tag"'}});});await detail();await click("Jadwalkan tindak lanjut");await userEvent.type(screen.getByLabelText(/Jenis tindak lanjut/),"Kunjungan bebas");await userEvent.type(screen.getByLabelText(/Waktu jadwal/),"2026-09-05T12:00");expect(screen.queryByRole("option",{name:"Rumah Sakit Tujuan"})).not.toBeInTheDocument();await click("Simpan jadwal");await screen.findByText(/Perubahan tersimpan/);expect(new Headers(calls.find(c=>c.url.endsWith("/follow-ups")&&c.options.method==="POST")!.options.headers).get("If-Match")).toBe('"actual-treatment-tag"');await click("Ubah metadata");await userEvent.type(screen.getByLabelText("Bentuk OAT"),"Bebas");await click("Simpan metadata");await screen.findByText(/Perubahan tersimpan/);expect(new Headers(calls.find(c=>c.options.method==="PATCH")!.options.headers).get("If-Match")).toBe('"advanced-treatment"');
});
it("follow-up completion uses child version and explicit fields",async()=>{const calls=treatmentBackend();await detail();await click("Selesaikan tindak lanjut 1");await userEvent.type(screen.getByLabelText(/Waktu selesai/),"2026-09-06T12:00");await userEvent.type(screen.getByLabelText("Ringkasan gejala"),"Narasi tanpa interpretasi");await click("Simpan penyelesaian");await screen.findByText(/Perubahan tersimpan/);const c=calls.find(c=>c.url.endsWith("/complete"))!;expect(new Headers(c.options.headers).get("If-Match")).toBe('"8"');expect(c.body?.symptomSummary).toBe("Narasi tanpa interpretasi");});
it("follow-up assigned outside actor facility cannot be completed",async()=>{treatmentBackend(c=>c.url.endsWith(treatmentIds.treatment)?Response.json({...treatmentDetail,followUps:[{...treatmentFollow,facility:{id:ids.destination,name:"Other"}}]}):undefined);await detail();await screen.findByText("Pasien Pengobatan");expect(screen.queryByRole("button",{name:"Selesaikan tindak lanjut 1"})).not.toBeInTheDocument();});
it("post-closure adverse edit uses child ETag and no immutable or unchanged timestamp fields",async()=>{const calls=treatmentBackend(c=>c.url.endsWith(treatmentIds.treatment)?Response.json({...treatmentDetail,status:"COMPLETED"}):undefined);await detail();await click("Ubah kejadian 1");await userEvent.type(screen.getByLabelText("Tingkat keparahan"),"Free severity");await click("Simpan kejadian");await screen.findByText(/Perubahan tersimpan/);const c=calls.find(c=>c.options.method==="PATCH")!;expect(c.body).toEqual({severity:"Free severity"});expect(new Headers(c.options.headers).get("If-Match")).toBe('"9"');});
it("adverse create requires explicit serious checkbox and no ETag",async()=>{const calls=treatmentBackend();await detail();await click("Catat kejadian tidak diinginkan");await userEvent.type(screen.getByLabelText(/Jenis kejadian/),"Keluhan bebas");await click("Simpan kejadian");await screen.findByText(/Perubahan tersimpan/);const c=calls.find(c=>c.options.method==="POST")!;expect(c.body?.serious).toBe(false);expect(new Headers(c.options.headers).has("If-Match")).toBe(false);});
it("duplicate dose conflict refetches paginated evidence and requires review without overwriting",async()=>{const calls=treatmentBackend(c=>c.options.method==="POST"?failure(409,"DOSE_EVENT_ALREADY_RECORDED"):undefined);await detail();await click("Catat bukti dosis");await userEvent.type(screen.getByLabelText(/Tanggal bukti dosis/),"2026-09-05");await userEvent.selectOptions(screen.getByLabelText(/Status bukti/),"MISSED");await click("Simpan bukti dosis");await screen.findByText("Bukti dosis sudah tercatat");expect(calls.filter(c=>c.options.method==="POST")).toHaveLength(1);expect(calls.filter(c=>c.url.includes("/dose-events?")).length).toBeGreaterThan(1);expect(screen.getByRole("button",{name:"Simpan bukti dosis"})).toBeDisabled();expect(screen.getByLabelText(/Tanggal bukti dosis/)).toHaveValue("2026-09-05");await click("Halaman dosis berikutnya");await waitFor(()=>expect(calls.some(c=>c.url.includes("page=1&size=20"))).toBe(true));});
it("outcome requires explicit closure confirmation, live code and actual treatment ETag",async()=>{
 let closed=false;const calls=treatmentBackend(c=>{if(c.url.endsWith("/outcome")){closed=true;return Response.json(treatmentOutcome);}if(c.url.endsWith(treatmentIds.treatment))return Response.json(closed?{...treatmentDetail,status:"COMPLETED",outcome:treatmentOutcome}:treatmentDetail,{headers:{ETag:'"actual-treatment-tag"'}});});await detail();await click("Catat hasil akhir");expect(screen.getByText("Pencatatan hasil akhir akan menutup episode pengobatan dan kasus ini.")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Simpan hasil akhir"})).toBeDisabled();await userEvent.selectOptions(screen.getByLabelText(/Kode hasil akhir/),"SEMBUH");await userEvent.type(screen.getByLabelText(/Tanggal hasil akhir/),"2026-09-10");await userEvent.click(screen.getByLabelText(/Saya mengonfirmasi penutupan/));await click("Simpan hasil akhir");await screen.findByText(/Perubahan tersimpan/);const c=calls.find(c=>c.url.endsWith("/outcome"))!;expect(c.body).toEqual({outcomeCode:"SEMBUH",outcomeDate:"2026-09-10",notes:null});expect(new Headers(c.options.headers).get("If-Match")).toBe('"actual-treatment-tag"');expect(screen.queryByRole("button",{name:"Catat hasil akhir"})).not.toBeInTheDocument();
});
it("source authority locks mounted editor and never exposes backend prose",async()=>{treatmentBackend(c=>c.options.method==="PATCH"?failure(409,"SOURCE_AUTHORITY_CONFLICT"):undefined);await detail();await click("Ubah metadata");await userEvent.type(screen.getByLabelText("Bentuk OAT"),"Private input");await click("Simpan metadata");await screen.findByText("Data dikendalikan sumber eksternal");expect(screen.getByRole("button",{name:"Simpan metadata"})).toBeDisabled();expect(screen.queryByText("private server details")).not.toBeInTheDocument();});
it("laboratory links are neutral and do not infer an outcome",async()=>{treatmentBackend();await detail();await screen.findByText("Pasien Pengobatan");const link=within(screen.getByRole("region",{name:"Laboratorium tindak lanjut"})).getByRole("link");expect(link).toHaveAttribute("href",`/laboratory/requests/${ids.diagnosis}`);expect(link).not.toHaveTextContent(ids.diagnosis);expect(screen.queryByText("Sembuh")).not.toBeInTheDocument();});
