import { z } from "@/lib/validation";
import { decimal } from "@/features/clinical-intake/forms/values";
import { optional,optionalDate } from "../contacts/forms";
import { todayLocal } from "../time";
import type { Tpt,Body,Dirty } from "../types";
export const tptFormSchema=z.object({regimenCode:z.string(),regimenDescription:z.string(),startDate:z.string(),plannedEndDate:optionalDate,durationValue:z.string().refine(v=>!v||(/^\d+$/.test(v)&&Number.isSafeInteger(Number(v))&&Number(v)>0&&Number(v)<=2147483647),"Durasi harus bilangan bulat positif."),durationUnit:optional(10),weightKg:decimal,drugSource:optional(100),notes:z.string()});
export const tptStartSchema=tptFormSchema.superRefine((v,c)=>{if(!z.iso.date().safeParse(v.startDate).success||v.startDate>todayLocal())c.addIssue({code:"custom",path:["startDate"],message:"Isi tanggal mulai yang valid dan tidak di masa depan."});if(!v.regimenCode&&!v.regimenDescription.trim())c.addIssue({code:"custom",path:["regimenDescription"],message:"Pilih paduan katalog atau isi deskripsi individual."});if(v.plannedEndDate&&v.plannedEndDate<v.startDate)c.addIssue({code:"custom",path:["plannedEndDate"],message:"Akhir rencana tidak boleh sebelum mulai."});});
export const tptEditSchema=(t:Tpt)=>tptFormSchema.superRefine((v,c)=>{if(!t.regimenCode&&!v.regimenDescription.trim())c.addIssue({code:"custom",path:["regimenDescription"],message:"Deskripsi individual merupakan satu-satunya paduan dan tidak dapat dihapus."});if(v.plannedEndDate&&v.plannedEndDate<t.startDate)c.addIssue({code:"custom",path:["plannedEndDate"],message:"Akhir rencana tidak boleh sebelum mulai."});});
export function tptValues(t?:Tpt){return {regimenCode:"",regimenDescription:t?.regimenDescription??"",startDate:t?.startDate??"",plannedEndDate:t?.plannedEndDate??"",durationValue:t?.durationValue==null?"":String(t.durationValue),durationUnit:t?.durationUnit??"",weightKg:t?.weightKg==null?"":String(t.weightKg),drugSource:t?.drugSource??"",notes:t?.notes??""};}
export function tptPatch(v:ReturnType<typeof tptValues>,dirty:Dirty):Body{const fields:Body={plannedEndDate:v.plannedEndDate||null,durationValue:v.durationValue?Number(v.durationValue):null,durationUnit:v.durationUnit||null,weightKg:v.weightKg?Number(v.weightKg):null,drugSource:v.drugSource.trim()||null,regimenDescription:v.regimenDescription.trim()||null,notes:v.notes.trim()||null};return Object.fromEntries(Object.entries(fields).filter(([key])=>dirty[key]===true));}
export function tptInput(v:ReturnType<typeof tptValues>):Body{const optional=tptPatch(v,{plannedEndDate:true,durationValue:true,durationUnit:true,weightKg:true,drugSource:true,regimenDescription:true,notes:true});return {...Object.fromEntries(Object.entries(optional).filter(([,v])=>v!==null)),startDate:v.startDate,...(v.regimenCode?{regimenCode:v.regimenCode}:{})};}
export type Closure="complete"|"stop"|"lost-to-follow-up";
export const closureValues=()=>({actualEndDate:"",closureReason:"",confirmed:false});
export const closureSchema=(action:Closure,startDate="")=>z.object({actualEndDate:optionalDate.refine(v=>!v||(v>=startDate&&v<=todayLocal()),"Tanggal akhir tidak valid."),closureReason:z.string(),confirmed:z.boolean().refine(Boolean,"Konfirmasi penutupan diperlukan.")}).refine(v=>action!=="stop"||!!v.closureReason.trim(),{path:["closureReason"],message:"Alasan penghentian wajib diisi."});
export function closureInput(v:ReturnType<typeof closureValues>):Body{return {...(v.actualEndDate?{actualEndDate:v.actualEndDate}:{}),...(v.closureReason.trim()?{closureReason:v.closureReason.trim()}:{})};}
